import Mathlib.Tactic.IntervalCases
import Mathlib.Tactic.FinCases
import TzapLean.Pass

/-!
# The `CancelGates` Pass

A port of `src/cancel.rs`. The Rust pass alternates three sweeps to a combined fixpoint:

1. **`cancelPairs`** — remove adjacent self-inverse pairs (`HH`, `XX`, `CNOT·CNOT`, …),
   commuting a gate past gates on non-overlapping wires to expose more pairs;
2. **`reduceHadamards`** — the local Clifford identities that lower the Hadamard count;
3. **`cancelCommutingPairs`** — cancel matching `CNOT`/`CZ` pairs across gates they commute
   with.

The Rust versions are index-and-scratch-buffer machines (per-qubit tracks, deletion stamps,
reused allocations); those are performance encodings of list surgery, so what is ported here
is the surgery. `cancelPairs` keeps the Rust structure exactly: a left-to-right scan with the
surviving prefix held in reverse, where the *blocker* — the most recent surviving gate
sharing a wire — is either the twin to cancel with or the reason the gate stays.

This section proves sweep 1. Each sweep is proved to preserve `denote`, and `CancelGates`
at the end of the file bundles the fixpoint as a `Pass`, so its correctness proof is a
field rather than a comment.
-/

namespace TzapLean

noncomputable section

/-! ## Overlap and gate matching -/

/-- The gates share a wire. `cancel_pairs` uses this to find the blocker. -/
def Gate.overlaps (g g' : Gate) : Bool := g.qubitsOf.any g'.support

theorem Wires.disjoint_of_not_overlaps {g g' : Gate} (h : g.overlaps g' = false) :
    Wires.Disjoint g.support g'.support := by
  intro q hq
  have hmem : q ∈ g.qubitsOf := (Gate.support_iff g q).mp hq
  simp only [Gate.overlaps, List.any_eq_false] at h
  simpa using h q hmem

/-- The Rust `gates_equal`: the two gates are the same gate, up to the operand symmetries
of `cz` (symmetric) and `ccz` (symmetric in all three operands). -/
def gatesEqual : Gate → Gate → Bool
  | .h a, .h b => a == b
  | .x a, .x b => a == b
  | .z a, .z b => a == b
  | .cnot c t, .cnot c' t' => c == c' && t == t'
  | .cz a b, .cz a' b' => (a == a' && b == b') || (a == b' && b == a')
  | .ccx a b c, .ccx a' b' c' => a == a' && b == b' && c == c'
  | .ccz a b c, .ccz a' b' c' =>
      (a == a' && b == b' && c == c') || (a == a' && b == c' && c == b') ||
      (a == b' && b == a' && c == c') || (a == b' && b == c' && c == a') ||
      (a == c' && b == a' && c == b') || (a == c' && b == b' && c == a')
  | _, _ => false

/-- `cz` is symmetric in its operands. -/
theorem gateUnitary_of_gatesEqual_cz (n : Nat) {a b a' b' : Qubit}
    (h : gatesEqual (.cz a b) (.cz a' b') = true) :
    gateUnitary n (.cz a b) = gateUnitary n (.cz a' b') := by
  simp only [gatesEqual, Bool.and_eq_true, Bool.or_eq_true, beq_iff_eq] at h
  rcases h with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
  · rfl
  · exact gateUnitary_cz_comm n _ _

/-- `ccz` is symmetric in all three operands. The six orderings are generated by the two
adjacent swaps. -/
theorem gateUnitary_of_gatesEqual_ccz (n : Nat) {a b c a' b' c' : Qubit}
    (h : gatesEqual (.ccz a b c) (.ccz a' b' c') = true) :
    gateUnitary n (.ccz a b c) = gateUnitary n (.ccz a' b' c') := by
  simp only [gatesEqual, Bool.and_eq_true, Bool.or_eq_true, beq_iff_eq] at h
  rcases h with ((((⟨⟨rfl, rfl⟩, rfl⟩ | ⟨⟨rfl, rfl⟩, rfl⟩) | ⟨⟨rfl, rfl⟩, rfl⟩) |
      ⟨⟨rfl, rfl⟩, rfl⟩) | ⟨⟨rfl, rfl⟩, rfl⟩) | ⟨⟨rfl, rfl⟩, rfl⟩
  · rfl
  · exact gateUnitary_ccz_swap₂₃ n _ _ _
  · exact gateUnitary_ccz_swap₁₂ n _ _ _
  · exact (gateUnitary_ccz_swap₂₃ n _ _ _).trans (gateUnitary_ccz_swap₁₂ n _ _ _)
  · exact (gateUnitary_ccz_swap₁₂ n _ _ _).trans (gateUnitary_ccz_swap₂₃ n _ _ _)
  · exact ((gateUnitary_ccz_swap₁₂ n _ _ _).trans (gateUnitary_ccz_swap₂₃ n _ _ _)).trans
      (gateUnitary_ccz_swap₁₂ n _ _ _)

/-- Matching gates have the same matrix: the `cz`/`ccz` symmetries are genuine identities,
not conventions. -/
theorem gateUnitary_of_gatesEqual (n : Nat) {g g' : Gate} (h : gatesEqual g g' = true) :
    gateUnitary n g = gateUnitary n g' := by
  cases g <;> cases g' <;>
    first
      | exact Bool.noConfusion h
      | exact gateUnitary_of_gatesEqual_cz n h
      | exact gateUnitary_of_gatesEqual_ccz n h
      | (simp only [gatesEqual, Bool.and_eq_true, beq_iff_eq] at h
         obtain ⟨⟨rfl, rfl⟩, rfl⟩ := h
         rfl)

/-! ## Sweep 1: adjacent self-inverse pairs -/

/-- Split the reversed surviving prefix at the *blocker*: the most recent gate sharing a
wire with `g`. Everything before it in the list (i.e. after it in the circuit) is disjoint
from `g`, which is what lets `g` commute back to it. -/
def splitBlocker (g : Gate) : List Gate → Option (List Gate × Gate × List Gate)
  | [] => none
  | a :: rest =>
      if g.overlaps a then some ([], a, rest)
      else (splitBlocker g rest).map fun x => (a :: x.1, x.2.1, x.2.2)

theorem splitBlocker_spec {g : Gate} :
    ∀ {acc pre b post}, splitBlocker g acc = some (pre, b, post) →
      acc = pre ++ b :: post ∧ (∀ a ∈ pre, g.overlaps a = false) := by
  intro acc
  induction acc with
  | nil => intro pre b post h; simp [splitBlocker] at h
  | cons a rest ih =>
      intro pre b post h
      simp only [splitBlocker] at h
      by_cases hov : g.overlaps a = true
      · rw [if_pos hov] at h
        simp only [Option.some.injEq, Prod.mk.injEq] at h
        obtain ⟨rfl, rfl, rfl⟩ := h
        exact ⟨rfl, by simp⟩
      · rw [if_neg hov] at h
        simp only [Option.map_eq_some_iff] at h
        obtain ⟨⟨pre', b', post'⟩, hsplit, heq⟩ := h
        simp only [Prod.mk.injEq] at heq
        obtain ⟨rfl, rfl, rfl⟩ := heq
        obtain ⟨hacc, hpre⟩ := ih hsplit
        refine ⟨by rw [hacc]; rfl, ?_⟩
        intro x hx
        rcases List.mem_cons.mp hx with rfl | hx
        · simpa using hov
        · exact hpre x hx

/-- One left-to-right sweep. `acc` is the surviving prefix, most recent first. -/
def cancelPairsAux : List Gate → List Gate → List Gate
  | acc, [] => acc.reverse
  | acc, g :: gs =>
      if g.isSelfInverse then
        match splitBlocker g acc with
        | some (pre, b, post) =>
            if gatesEqual b g then cancelPairsAux (pre ++ post) gs
            else cancelPairsAux (g :: acc) gs
        | none => cancelPairsAux (g :: acc) gs
      else cancelPairsAux (g :: acc) gs

/-- Remove adjacent self-inverse pairs, commuting gates past non-overlapping operands. -/
def cancelPairs (gs : List Gate) : List Gate := cancelPairsAux [] gs

theorem isUnitary_of_gatesEqual {b g : Gate} (h : gatesEqual b g = true) :
    b.isUnitary = true ∧ g.isUnitary = true := by
  cases b <;> cases g <;> first | exact Bool.noConfusion h | exact ⟨rfl, rfl⟩

theorem isUnitary_of_isSelfInverse {g : Gate} (h : g.isSelfInverse = true) :
    g.isUnitary = true := by
  cases g <;> first | rfl | exact Bool.noConfusion h

/-- A gate cancels against a matching earlier gate. -/
theorem Equivalent.gatesEqual_cancel {n m : Nat} {b g : Gate} (heq : gatesEqual b g = true)
    (hwf : g.Wf) (hsi : g.isSelfInverse = true) : Equivalent n m [b, g] [] := by
  obtain ⟨hub, hug⟩ := isUnitary_of_gatesEqual heq
  refine equivalent_of_unitary_eq ?_ (by simp) ?_
  · intro x hx
    rcases List.mem_cons.mp hx with rfl | hx
    · exact hub
    · rcases List.mem_cons.mp hx with rfl | hx
      · exact hug
      · simp at hx
  · simp only [unitary_cons, unitary_nil, Matrix.one_mul]
    rw [gateUnitary_of_gatesEqual n heq]
    exact gateUnitary_mul_self n g hwf hsi

/-- Equation lemma for the sweep's recursion. -/
theorem cancelPairsAux_cons (acc : List Gate) (g : Gate) (gs : List Gate) :
    cancelPairsAux acc (g :: gs) =
      if g.isSelfInverse then
        match splitBlocker g acc with
        | some (pre, b, post) =>
            if gatesEqual b g then cancelPairsAux (pre ++ post) gs
            else cancelPairsAux (g :: acc) gs
        | none => cancelPairsAux (g :: acc) gs
      else cancelPairsAux (g :: acc) gs := rfl

/-- The rewrite one cancellation performs: the incoming gate `g` commutes back over the
disjoint run `pre` and annihilates the blocker `b`. -/
theorem cancel_window {n m : Nat} {g b : Gate} (pre post gs : List Gate)
    (hu : g.isUnitary = true) (hdisj : ∀ a ∈ pre, Wires.Disjoint g.support a.support)
    (heq : gatesEqual b g = true) (hwf : g.Wf) (hsi : g.isSelfInverse = true) :
    Equivalent n m (post ++ (b :: (pre ++ (g :: gs)))) (post ++ (pre ++ gs)) := by
  refine Equivalent.append_left post ?_
  have m1 : Equivalent n m (pre ++ (g :: gs)) ((g :: pre) ++ gs) := by
    have h := Equivalent.append_right (n := n) (m := m) gs
      (Equivalent.move_past (n := n) (m := m) hu pre hdisj)
    simpa [List.append_assoc] using h
  have m2 : Equivalent n m (b :: (pre ++ (g :: gs))) (b :: ((g :: pre) ++ gs)) := by
    have := Equivalent.append_left (n := n) (m := m) [b] m1
    simpa using this
  have m3 : Equivalent n m ([b, g] ++ (pre ++ gs)) ([] ++ (pre ++ gs)) :=
    Equivalent.append_right _ (Equivalent.gatesEqual_cancel heq hwf hsi)
  refine Equivalent.trans m2 ?_
  simpa using m3

/-- **Sweep 1 is semantics preserving.** The blocker is either the twin that cancels — with
everything after it disjoint from the incoming gate, so the gate commutes back to it — or
the gate stays. -/
theorem cancelPairsAux_correct {n m : Nat} (acc gs : List Gate) (hwf : ∀ g ∈ gs, g.Wf) :
    Equivalent n m (cancelPairsAux acc gs) (acc.reverse ++ gs) := by
  induction gs generalizing acc with
  | nil => simpa [cancelPairsAux] using Equivalent.refl n m acc.reverse
  | cons g gs ih =>
      have hwf' : ∀ g' ∈ gs, g'.Wf := fun g' hg' => hwf g' (by simp [hg'])
      have keep : Equivalent n m (cancelPairsAux (g :: acc) gs) (acc.reverse ++ g :: gs) := by
        have h := ih (g :: acc) hwf'
        simpa [List.reverse_cons, List.append_assoc] using h
      rw [cancelPairsAux_cons]
      by_cases hsi : g.isSelfInverse = true
      · rw [if_pos hsi]
        cases hsplit : splitBlocker g acc with
        | none => exact keep
        | some triple =>
            obtain ⟨pre, b, post⟩ := triple
            dsimp only
            by_cases heq : gatesEqual b g = true
            · rw [if_pos heq]
              obtain ⟨hacc, hpre⟩ := splitBlocker_spec hsplit
              have hu : g.isUnitary = true := isUnitary_of_isSelfInverse hsi
              have hdisj : ∀ a ∈ pre.reverse, Wires.Disjoint g.support a.support := by
                intro a ha
                exact Wires.disjoint_of_not_overlaps
                  (by simpa using hpre a (List.mem_reverse.mp ha))
              have hwin := cancel_window (n := n) (m := m) (g := g) (b := b)
                pre.reverse post.reverse gs hu hdisj heq (hwf g (by simp)) hsi
              refine Equivalent.trans (ih (pre ++ post) hwf') ?_
              rw [hacc]
              simpa [List.reverse_append, List.append_assoc] using hwin.symm
            · rw [if_neg heq]
              exact keep
      · rw [if_neg hsi]
        exact keep

/-- The sweep only ever keeps gates it was given. -/
theorem cancelPairsAux_mem (acc gs : List Gate) :
    ∀ g ∈ cancelPairsAux acc gs, g ∈ acc ∨ g ∈ gs := by
  induction gs generalizing acc with
  | nil => intro g hg; left; simpa [cancelPairsAux] using hg
  | cons g' gs ih =>
      intro g hg
      rw [cancelPairsAux_cons] at hg
      have keep : ∀ x ∈ cancelPairsAux (g' :: acc) gs, x ∈ acc ∨ x ∈ g' :: gs := by
        intro x hx
        rcases ih (g' :: acc) x hx with h | h
        · rcases List.mem_cons.mp h with rfl | h
          · right; simp
          · left; exact h
        · right; simp [h]
      by_cases hsi : g'.isSelfInverse = true
      · rw [if_pos hsi] at hg
        cases hsplit : splitBlocker g' acc with
        | none => rw [hsplit] at hg; exact keep g hg
        | some triple =>
            obtain ⟨pre, b, post⟩ := triple
            rw [hsplit] at hg
            dsimp only at hg
            by_cases heq : gatesEqual b g' = true
            · rw [if_pos heq] at hg
              obtain ⟨hacc, -⟩ := splitBlocker_spec hsplit
              rcases ih (pre ++ post) g hg with h | h
              · left
                rw [hacc]
                rcases List.mem_append.mp h with h | h
                · exact List.mem_append_left _ h
                · exact List.mem_append_right _ (List.mem_cons_of_mem _ h)
              · right; simp [h]
            · rw [if_neg heq] at hg
              exact keep g hg
      · rw [if_neg hsi] at hg
        exact keep g hg

theorem cancelPairs_correct {n m : Nat} (gs : List Gate) (hwf : ∀ g ∈ gs, g.Wf) :
    Equivalent n m (cancelPairs gs) gs := by
  simpa [cancelPairs] using cancelPairsAux_correct (n := n) (m := m) [] gs hwf

theorem cancelPairs_mem (gs : List Gate) : ∀ g ∈ cancelPairs gs, g ∈ gs := by
  intro g hg
  rcases cancelPairsAux_mem [] gs g hg with h | h
  · simp at h
  · exact h

/-! ## Sweep 2: Hadamard reduction

The local Clifford identities of `reduce_hadamards`:

```
H·H = I      H·X·H = Z      H·D·H = X        (D ≡ Z)
             H·D·H = I      H·D·H = Sdg·H·Sdg (D ≡ S)     H·D·H = S·H·S (D ≡ Sdg)
```

`D` is a maximal run of diagonal gates on the wire, so each identity is local to that wire
regardless of what happens on the others — which is why the scan below carries the
untouched gates along and puts the rewritten gate back where the run started, exactly as
the Rust in-place replacement does.
-/

/-- `g` is `h q`. -/
def isH (q : Qubit) : Gate → Bool
  | .h p => p == q
  | _ => false

/-- `g` is `x q`. -/
def isX (q : Qubit) : Gate → Bool
  | .x p => p == q
  | _ => false

/-- The Rust `classify_quarter_pi`: an `rz` angle of `θ·π` is `k·π/4` when `4θ` is an
integer, and then `k = 4θ mod 8`. -/
def classifyQuarterPi (θ : ℚ) : Option Nat :=
  let x : ℚ := 4 * θ
  if x.den = 1 then some (((x.num % 8 + 8) % 8).toNat) else none

/-- The Rust `diagonal_k`: `some (some k)` for a diagonal gate on `q` rotating by `k·π/4`,
`some none` for a diagonal `rz` at a non-`π/4` angle, `none` for anything else. -/
def diagonalK (g : Gate) (q : Qubit) : Option (Option Nat) :=
  match g with
  | .t p => if p == q then some (some 1) else none
  | .tdg p => if p == q then some (some 7) else none
  | .s p => if p == q then some (some 2) else none
  | .sdg p => if p == q then some (some 6) else none
  | .z p => if p == q then some (some 4) else none
  | .rz θ p => if p == q then some (classifyQuarterPi θ) else none
  | _ => none

/-- A canonical gate list realizing the rotation `k·π/4` on wire `q`. -/
def diagRun : Nat → Qubit → List Gate
  | 0, _ => []
  | 1, q => [.t q]
  | 2, q => [.s q]
  | 3, q => [.s q, .t q]
  | 4, q => [.z q]
  | 5, q => [.z q, .t q]
  | 6, q => [.sdg q]
  | 7, q => [.tdg q]
  | _, _ => []

/-- The result of scanning a wire from just after an opening `h`. -/
structure HScan where
  /-- Total rotation of the diagonal run, in units of `π/4`, mod 8. -/
  k : Nat
  /-- Gates not touching the wire, before the run's first gate. -/
  before : List Gate
  /-- Gates not touching the wire, from the run's first gate to the closing `h`. -/
  after : List Gate
  /-- What follows the closing `h`. -/
  rest : List Gate
  /-- Whether the run is non-empty. -/
  hasRun : Bool
  deriving Repr

/-- Carry a gate that misses the wire along the scan, keeping it on the correct side of the
run's first gate. -/
def HScan.push (g : Gate) (r : HScan) : HScan :=
  if r.hasRun then { r with before := g :: r.before } else { r with after := g :: r.after }

theorem HScan.push_of_hasRun {g : Gate} {r : HScan} (h : r.hasRun = true) :
    HScan.push g r = { r with before := g :: r.before } := by simp [HScan.push, h]

theorem HScan.push_of_not_hasRun {g : Gate} {r : HScan} (h : r.hasRun = false) :
    HScan.push g r = { r with after := g :: r.after } := by simp [HScan.push, h]

/-- Scan the wire for `h · (maximal diagonal run) · h`, carrying untouched gates along.
Fails (`none`) at any other gate on the wire, including a non-`π/4` `rz`. -/
def scanH (q : Qubit) : List Gate → Option HScan
  | [] => none
  | g :: gs =>
      if g.support q then
        match diagonalK g q with
        | some (some kg) =>
            (scanH q gs).map fun r =>
              { k := (kg + r.k) % 8, before := [], after := r.before ++ r.after,
                rest := r.rest, hasRun := true }
        | some none => none
        | none =>
            if isH q g then
              some { k := 0, before := [], after := [], rest := gs, hasRun := false }
            else none
      else (scanH q gs).map (HScan.push g)

/-- The next gate on the wire is `h q`; returns the untouched gates passed and the rest. -/
def scanHOnly (q : Qubit) : List Gate → Option (List Gate × List Gate)
  | [] => none
  | g :: gs =>
      if g.support q then (if isH q g then some ([], gs) else none)
      else (scanHOnly q gs).map fun r => (g :: r.1, r.2)

/-- The wire continues `x q` then `h q` — the `H·X·H` pattern. -/
def scanXH (q : Qubit) : List Gate → Option (List Gate × List Gate × List Gate)
  | [] => none
  | g :: gs =>
      if g.support q then
        (if isX q g then (scanHOnly q gs).map fun r => ([], r.1, r.2) else none)
      else (scanXH q gs).map fun r => (g :: r.1, r.2.1, r.2.2)

/-- Try every Hadamard-reduction rule at an opening `h q`; `gs` is what follows it. -/
def reduceAtH (q : Qubit) (gs : List Gate) : Option (List Gate) :=
  match scanXH q gs with
  | some (b₁, b₂, rest) => some (b₁ ++ Gate.z q :: b₂ ++ rest)
  | none =>
      match scanH q gs with
      | none => none
      | some r =>
          if r.k % 2 = 1 then none
          else if r.k = 0 then some (r.before ++ r.after ++ r.rest)
          else if r.k = 4 then some (r.before ++ Gate.x q :: r.after ++ r.rest)
          else if r.k = 2 then
            some (Gate.sdg q :: r.before ++ Gate.h q :: r.after ++ Gate.sdg q :: r.rest)
          else some (Gate.s q :: r.before ++ Gate.h q :: r.after ++ Gate.s q :: r.rest)

/-- One rewrite anywhere in the list, or `none` at the fixpoint. -/
def reduceStep : List Gate → Option (List Gate)
  | [] => none
  | g :: gs =>
      match g with
      | .h q =>
          match reduceAtH q gs with
          | some out => some out
          | none => (reduceStep gs).map (g :: ·)
      | _ => (reduceStep gs).map (g :: ·)

/-- Iterate `reduceStep`. Every rewrite removes at least one `h`, so `gs.length` steps
always reach the fixpoint (the Rust loop's termination argument, made explicit). -/
def reduceHadamardsFuel : Nat → List Gate → List Gate
  | 0, gs => gs
  | fuel + 1, gs =>
      match reduceStep gs with
      | some gs' => reduceHadamardsFuel fuel gs'
      | none => gs

/-- Apply the Hadamard-reduction identities to a fixpoint. -/
def reduceHadamards (gs : List Gate) : List Gate := reduceHadamardsFuel gs.length gs

/-! ### Gates on a single wire -/

/-- `g` acts on the single wire `q` (and is therefore unitary). -/
def OnWire (q : Qubit) : Gate → Prop
  | .h p | .x p | .s p | .sdg p | .z p | .t p | .tdg p | .rz _ p => p = q
  | _ => False

theorem OnWire.support {q : Qubit} {g : Gate} (h : OnWire q g) :
    g.support = fun r => r == q := by
  cases g <;> simp only [OnWire] at h <;> subst h <;> rfl

theorem OnWire.isUnitary {q : Qubit} {g : Gate} (h : OnWire q g) : g.isUnitary = true := by
  cases g <;> simp only [OnWire] at h <;> rfl

theorem OnWire.gateUnitary_eq_one {n q : Nat} {g : Gate} (h : OnWire q g) (hq : ¬ q < n) :
    gateUnitary n g = 1 := by
  cases g <;> simp only [OnWire] at h <;> subst h <;>
    simp [gateUnitary, embed1_eq_one _ hq]

/-- A one-wire gate is disjoint from anything that misses its wire. -/
theorem disjoint_of_onWire {q : Qubit} {g g' : Gate} (hg : OnWire q g)
    (h : g'.support q = false) : Wires.Disjoint g.support g'.support := by
  intro r hr
  rw [hg.support] at hr
  have : r = q := by simpa using hr
  subst this
  exact h

theorem unitary_eq_one_of_onWire {n : Nat} {q : Qubit} (hq : ¬ q < n) :
    ∀ gs : List Gate, (∀ g ∈ gs, OnWire q g) → unitary n gs = 1
  | [], _ => rfl
  | g :: gs, h => by
      rw [unitary_cons, unitary_eq_one_of_onWire hq gs fun g' hg' => h g' (by simp [hg']),
        (h g (by simp)).gateUnitary_eq_one hq, Matrix.one_mul]

/-! ### The canonical diagonal run -/

theorem diagRun_onWire (k : Nat) (q : Qubit) : ∀ g ∈ diagRun k q, OnWire q g := by
  match k with
  | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 => intro g hg; fin_cases hg <;> rfl
  | (n + 8) => intro g hg; simp [diagRun] at hg

theorem unitary_diagRun (n : Nat) (q : Qubit) :
    ∀ k, k < 8 → unitary n (diagRun k q) = embed1 n (diag2 1 (ep ((k : ℚ) / 4))) q := by
  intro k hk
  interval_cases k
  all_goals
    simp only [diagRun, unitary_nil, unitary_cons, gateUnitary, embed1_mul,
      mul2_diag2, one_mul, Nat.cast_ofNat, Nat.cast_one, Nat.cast_zero]
  all_goals try rw [← ep_add]
  all_goals try norm_num
  all_goals try rw [show ((3 : ℚ)/2) = -(1/2) + 2 by norm_num, ep_add_two]
  all_goals try rw [show ((7 : ℚ)/4) = -(1/4) + 2 by norm_num, ep_add_two]

/-- **The one-wire rewrite principle.** Two gate lists confined to a single wire are
equivalent as soon as their matrices agree up to phase on that wire — and if the wire is
out of range, both are the identity and there is nothing to check. -/
theorem Equivalent.of_onWire {n m : Nat} {q : Qubit} {gs hs : List Gate}
    (hg : ∀ g ∈ gs, OnWire q g) (hh : ∀ g ∈ hs, OnWire q g)
    (c : ℂ) (hc : c * star c = 1)
    (h : q < n → unitary n gs = c • unitary n hs) : Equivalent n m gs hs := by
  by_cases hq : q < n
  · exact equivalent_of_unitary_smul (fun g hg' => (hg g hg').isUnitary)
      (fun g hh' => (hh g hh').isUnitary) c hc (h hq)
  · refine equivalent_of_unitary_eq (fun g hg' => (hg g hg').isUnitary)
      (fun g hh' => (hh g hh').isUnitary) ?_
    rw [unitary_eq_one_of_onWire hq gs hg, unitary_eq_one_of_onWire hq hs hh]

/-! ### `rz` angles that are multiples of `π/4` -/

theorem ep_two_mul_int (j : ℤ) : ep (2 * (j : ℚ)) = 1 := by
  have : ep (2 * (j : ℚ)) = Complex.exp ((j : ℂ) * (2 * (Real.pi : ℂ) * Complex.I)) := by
    simp only [ep]
    congr 1
    push_cast
    ring
  rw [this, Complex.exp_int_mul, Complex.exp_two_pi_mul_I, one_zpow]

theorem classifyQuarterPi_lt {θ : ℚ} {k : Nat} (h : classifyQuarterPi θ = some k) : k < 8 := by
  simp only [classifyQuarterPi] at h
  split at h
  · rename_i hden
    have h' : (((4 * θ).num % 8 + 8) % 8).toNat = k := by simpa using h
    subst h'
    have hlt : ((4 * θ).num % 8 + 8) % 8 < 8 := Int.emod_lt_of_pos _ (by norm_num)
    omega
  · exact absurd h (by simp)

theorem ep_of_classifyQuarterPi {θ : ℚ} {k : Nat} (h : classifyQuarterPi θ = some k) :
    ep θ = ep ((k : ℚ) / 4) := by
  simp only [classifyQuarterPi] at h
  split at h
  · rename_i hden
    have hk : (((4 * θ).num % 8 + 8) % 8).toNat = k := by simpa using h
    set N : ℤ := (4 * θ).num with hN
    have hθ : (4 : ℚ) * θ = (N : ℚ) := by
      rw [hN]; exact ((Rat.den_eq_one_iff _).mp hden).symm
    have hnonneg : 0 ≤ (N % 8 + 8) % 8 := Int.emod_nonneg _ (by norm_num)
    have hkval : ((k : ℤ)) = (N % 8 + 8) % 8 := by
      rw [← hk]; exact Int.toNat_of_nonneg hnonneg
    obtain ⟨j, hj⟩ : ∃ j : ℤ, N = 8 * j + (k : ℤ) := ⟨N / 8, by omega⟩
    have hθ' : θ = 2 * (j : ℚ) + (k : ℚ) / 4 := by
      have h4 : (4 : ℚ) * θ = 8 * (j : ℚ) + (k : ℚ) := by
        rw [hθ, hj]; push_cast; ring
      linarith
    rw [hθ', ep_add, ep_two_mul_int, one_mul]
  · exact absurd h (by simp)

theorem ep_quarter_mod (a : Nat) : ep ((a : ℚ)/4) = ep (((a % 8 : Nat) : ℚ)/4) := by
  have hsplit : (a : ℚ) = 8 * ((a / 8 : Nat) : ℚ) + ((a % 8 : Nat) : ℚ) := by
    exact_mod_cast congrArg (fun x : Nat => (x : ℚ)) (Nat.div_add_mod a 8).symm
  have h : (a : ℚ)/4 = 2 * ((a / 8 : Nat) : ℚ) + ((a % 8 : Nat) : ℚ)/4 := by
    rw [hsplit]; ring
  have hone : ep (2 * ((a / 8 : Nat) : ℚ)) = 1 := by
    have := ep_two_mul_int ((a / 8 : Nat) : ℤ)
    rwa [Int.cast_natCast] at this
  rw [h, ep_add, hone, one_mul]

theorem diagonalK_onWire {g : Gate} {q : Qubit} {x : Option Nat} (h : diagonalK g q = some x) :
    OnWire q g := by
  cases g with
  | t p | tdg p | s p | sdg p | z p =>
      simp only [diagonalK] at h
      split at h
      · rename_i hp; exact (by simpa using hp : p = q)
      · simp at h
  | rz θ p =>
      simp only [diagonalK] at h
      split at h
      · rename_i hp; exact (by simpa using hp : p = q)
      · simp at h
  | _ => simp [diagonalK] at h

theorem diagonalK_lt {g : Gate} {q : Qubit} {k : Nat} (h : diagonalK g q = some (some k)) :
    k < 8 := by
  cases g with
  | t p | tdg p | s p | sdg p | z p =>
      simp only [diagonalK] at h
      split at h
      · simp at h; omega
      · simp at h
  | rz θ p =>
      simp only [diagonalK] at h
      split at h
      · exact classifyQuarterPi_lt (by simpa using h)
      · simp at h
  | _ => simp [diagonalK] at h

/-- **A diagonal gate is its canonical run.** For `rz` this is where the angle convention
`rz θ = diag(e^{-iπθ/2}, e^{iπθ/2})` shows up: it differs from `diag(1, e^{iπθ})` by a
global phase, which the channel semantics discards. -/
theorem Equivalent.diagonal_gate {n m : Nat} {g : Gate} {q : Qubit} {k : Nat}
    (h : diagonalK g q = some (some k)) : Equivalent n m [g] (diagRun k q) := by
  cases g with
  | t p =>
      simp only [diagonalK] at h
      split at h
      · rename_i hp
        have hpq : p = q := (by simpa using hp : p = q)
        have hk : k = 1 := by simp at h; omega
        rw [hpq, hk]
        exact Equivalent.refl _ _ _
      · simp at h
  | tdg p =>
      simp only [diagonalK] at h
      split at h
      · rename_i hp
        have hpq : p = q := (by simpa using hp : p = q)
        have hk : k = 7 := by simp at h; omega
        rw [hpq, hk]
        exact Equivalent.refl _ _ _
      · simp at h
  | s p =>
      simp only [diagonalK] at h
      split at h
      · rename_i hp
        have hpq : p = q := (by simpa using hp : p = q)
        have hk : k = 2 := by simp at h; omega
        rw [hpq, hk]
        exact Equivalent.refl _ _ _
      · simp at h
  | sdg p =>
      simp only [diagonalK] at h
      split at h
      · rename_i hp
        have hpq : p = q := (by simpa using hp : p = q)
        have hk : k = 6 := by simp at h; omega
        rw [hpq, hk]
        exact Equivalent.refl _ _ _
      · simp at h
  | z p =>
      simp only [diagonalK] at h
      split at h
      · rename_i hp
        have hpq : p = q := (by simpa using hp : p = q)
        have hk : k = 4 := by simp at h; omega
        rw [hpq, hk]
        exact Equivalent.refl _ _ _
      · simp at h
  | rz θ p =>
      simp only [diagonalK] at h
      split at h
      · rename_i hp
        have hpq : p = q := (by simpa using hp : p = q)
        have hcl : classifyQuarterPi θ = some k := by simpa using h
        have hk8 : k < 8 := classifyQuarterPi_lt hcl
        rw [hpq]
        refine Equivalent.of_onWire (q := q) (fun g' hg' => by
            rcases List.mem_singleton.mp hg' with rfl
            exact (rfl : q = q))
          (fun g' hg' => diagRun_onWire k q g' hg') (ep (-θ/2)) (ep_mul_star _) ?_
        intro hq
        rw [unitary_diagRun n q k hk8, ← embed1_smul _ _ _ hq]
        simp only [unitary_cons, unitary_nil, Matrix.one_mul, gateUnitary]
        congr 1
        funext o i
        have hphase : ep (-θ/2) * ep ((k : ℚ)/4) = ep (θ/2) := by
          rw [← ep_of_classifyQuarterPi hcl, ← ep_add]
          congr 1
          ring
        cases o <;> cases i <;> simp [diag2, hphase]
      · simp at h
  | _ => simp [diagonalK] at h

/-- Two canonical runs on the same wire merge, modulo `2π`. -/
theorem Equivalent.diagRun_append {n m : Nat} (k k' : Nat) (q : Qubit)
    (hk : k < 8) (hk' : k' < 8) :
    Equivalent n m (diagRun k q ++ diagRun k' q) (diagRun ((k + k') % 8) q) := by
  refine Equivalent.of_onWire (q := q)
    (fun g hg => by
      rcases List.mem_append.mp hg with h | h
      · exact diagRun_onWire k q g h
      · exact diagRun_onWire k' q g h)
    (fun g hg => diagRun_onWire _ q g hg) 1 (by simp) ?_
  intro hq
  rw [one_smul, unitary_append, unitary_diagRun n q k hk, unitary_diagRun n q k' hk',
    unitary_diagRun n q _ (Nat.mod_lt _ (by norm_num)), embed1_mul, mul2_diag2, one_mul,
    ← ep_add]
  congr 2
  rw [show ((k' : ℚ)/4 + (k : ℚ)/4) = ((k + k' : Nat) : ℚ)/4 by push_cast; ring]
  exact ep_quarter_mod (k + k')

/-! ### The Hadamard identities as circuit equivalences -/

private theorem onWire_list {q : Qubit} : ∀ (gs : List Gate),
    (∀ g ∈ gs, OnWire q g) → ∀ g ∈ gs, OnWire q g := fun _ h => h

/-- `H·H = I`. -/
theorem Equivalent.hh {n m : Nat} (q : Qubit) :
    Equivalent n m [Gate.h q, Gate.h q] [] := by
  refine Equivalent.of_onWire (q := q) (by intro g hg; fin_cases hg <;> rfl) (by simp)
    1 (by simp) fun _ => ?_
  simp only [unitary_cons, unitary_nil, Matrix.one_mul, gateUnitary, one_smul, embed1_mul,
    mul2_h2, embed1_id2]

/-- `H·X·H = Z`. -/
theorem Equivalent.hxh {n m : Nat} (q : Qubit) :
    Equivalent n m [Gate.h q, Gate.x q, Gate.h q] [Gate.z q] := by
  refine Equivalent.of_onWire (q := q) (by intro g hg; fin_cases hg <;> rfl)
    (by intro g hg; fin_cases hg; rfl) 1 (by simp) fun _ => ?_
  simp only [unitary_cons, unitary_nil, Matrix.one_mul, gateUnitary, one_smul, embed1_mul,
    mul2_hxh]

/-- `H·Z·H = X`. -/
theorem Equivalent.hzh {n m : Nat} (q : Qubit) :
    Equivalent n m [Gate.h q, Gate.z q, Gate.h q] [Gate.x q] := by
  refine Equivalent.of_onWire (q := q) (by intro g hg; fin_cases hg <;> rfl)
    (by intro g hg; fin_cases hg; rfl) 1 (by simp) fun _ => ?_
  simp only [unitary_cons, unitary_nil, Matrix.one_mul, gateUnitary, one_smul, embed1_mul,
    mul2_hzh]

/-- `H·S·H = Sdg·H·Sdg`, up to the global phase `e^{iπ/4}`. -/
theorem Equivalent.hsh {n m : Nat} (q : Qubit) :
    Equivalent n m [Gate.h q, Gate.s q, Gate.h q] [Gate.sdg q, Gate.h q, Gate.sdg q] := by
  refine Equivalent.of_onWire (q := q) (by intro g hg; fin_cases hg <;> rfl)
    (by intro g hg; fin_cases hg <;> rfl) (ep (1/4)) (ep_mul_star _) fun hq => ?_
  simp only [unitary_cons, unitary_nil, Matrix.one_mul, gateUnitary, embed1_mul]
  rw [mul2_hsh, embed1_smul _ _ _ hq]

/-- `H·Sdg·H = S·H·S`, up to the global phase `e^{-iπ/4}`. -/
theorem Equivalent.hsdgh {n m : Nat} (q : Qubit) :
    Equivalent n m [Gate.h q, Gate.sdg q, Gate.h q] [Gate.s q, Gate.h q, Gate.s q] := by
  refine Equivalent.of_onWire (q := q) (by intro g hg; fin_cases hg <;> rfl)
    (by intro g hg; fin_cases hg <;> rfl) (ep (-1/4)) (ep_mul_star _) fun hq => ?_
  simp only [unitary_cons, unitary_nil, Matrix.one_mul, gateUnitary, embed1_mul]
  rw [mul2_hsdgh, embed1_smul _ _ _ hq]

/-! ### What the scans found -/

theorem scanHOnly_spec {q : Qubit} : ∀ {gs others rest : List Gate},
    scanHOnly q gs = some (others, rest) →
      gs = others ++ Gate.h q :: rest ∧ ∀ g ∈ others, g.support q = false := by
  intro gs
  induction gs with
  | nil => intro others rest h; simp [scanHOnly] at h
  | cons g gs ih =>
      intro others rest h
      simp only [scanHOnly] at h
      by_cases hs : g.support q = true
      · rw [if_pos hs] at h
        by_cases hh : isH q g = true
        · rw [if_pos hh] at h
          have hg : g = Gate.h q := by
            cases g <;> simp only [isH] at hh <;> simp_all
          simp only [Option.some.injEq, Prod.mk.injEq] at h
          obtain ⟨rfl, rfl⟩ := h
          exact ⟨by rw [hg]; rfl, by simp⟩
        · rw [if_neg hh] at h; simp at h
      · rw [if_neg hs] at h
        simp only [Option.map_eq_some_iff] at h
        obtain ⟨⟨others', rest'⟩, hscan, heq⟩ := h
        simp only [Prod.mk.injEq] at heq
        obtain ⟨rfl, rfl⟩ := heq
        obtain ⟨hgs, hsupp⟩ := ih hscan
        refine ⟨by rw [hgs]; rfl, ?_⟩
        intro x hx
        rcases List.mem_cons.mp hx with rfl | hx
        · simpa using hs
        · exact hsupp x hx

theorem scanXH_spec {q : Qubit} : ∀ {gs b₁ b₂ rest : List Gate},
    scanXH q gs = some (b₁, b₂, rest) →
      gs = b₁ ++ Gate.x q :: (b₂ ++ Gate.h q :: rest) ∧
      (∀ g ∈ b₁, g.support q = false) ∧ (∀ g ∈ b₂, g.support q = false) := by
  intro gs
  induction gs with
  | nil => intro b₁ b₂ rest h; simp [scanXH] at h
  | cons g gs ih =>
      intro b₁ b₂ rest h
      simp only [scanXH] at h
      by_cases hs : g.support q = true
      · rw [if_pos hs] at h
        by_cases hx : isX q g = true
        · rw [if_pos hx] at h
          have hg : g = Gate.x q := by
            cases g <;> simp only [isX] at hx <;> simp_all
          simp only [Option.map_eq_some_iff] at h
          obtain ⟨⟨others, rest'⟩, hscan, heq⟩ := h
          simp only [Prod.mk.injEq] at heq
          obtain ⟨rfl, rfl, rfl⟩ := heq
          obtain ⟨hgs, hsupp⟩ := scanHOnly_spec hscan
          exact ⟨by rw [hg, hgs]; simp, by simp, hsupp⟩
        · rw [if_neg hx] at h; simp at h
      · rw [if_neg hs] at h
        simp only [Option.map_eq_some_iff] at h
        obtain ⟨⟨b₁', b₂', rest'⟩, hscan, heq⟩ := h
        simp only [Prod.mk.injEq] at heq
        obtain ⟨rfl, rfl, rfl⟩ := heq
        obtain ⟨hgs, h1, h2⟩ := ih hscan
        refine ⟨by rw [hgs]; rfl, ?_, h2⟩
        intro x hx
        rcases List.mem_cons.mp hx with rfl | hx
        · simpa using hs
        · exact h1 x hx

/-- **What a successful wire scan means.** The window is the untouched gates (in order),
a diagonal run worth `k·π/4`, and the closing `h` — up to commuting the run past the gates
it shares no wire with. -/
theorem scanH_spec {n m : Nat} {q : Qubit} : ∀ {gs : List Gate} {r : HScan},
    scanH q gs = some r →
      (∀ g ∈ r.before ++ r.after, g.support q = false) ∧ r.k < 8 ∧
      (r.hasRun = false → r.before = []) ∧
      Equivalent n m gs (r.before ++ r.after ++ (diagRun r.k q ++ Gate.h q :: r.rest)) := by
  intro gs
  induction gs with
  | nil => intro r h; simp [scanH] at h
  | cons g gs ih =>
      intro r h
      simp only [scanH] at h
      by_cases hs : g.support q = true
      · rw [if_pos hs] at h
        rcases hd : diagonalK g q with _ | dk
        · rw [hd] at h
          by_cases hh : isH q g = true
          · rw [if_pos hh] at h
            have hg : g = Gate.h q := by
              cases g <;> simp only [isH] at hh <;> simp_all
            simp only [Option.some.injEq] at h
            subst h
            refine ⟨by simp, by norm_num, fun _ => rfl, ?_⟩
            simp only [diagRun, List.nil_append, List.append_nil]
            rw [hg]
          · rw [if_neg hh] at h; simp at h
        · rcases dk with _ | kg
          · rw [hd] at h; simp at h
          · rw [hd] at h
            simp only [Option.map_eq_some_iff] at h
            obtain ⟨r', hscan, rfl⟩ := h
            obtain ⟨hsupp, hk8, _, hequiv⟩ := ih hscan
            have hw : OnWire q g := diagonalK_onWire hd
            have hkg8 : kg < 8 := diagonalK_lt hd
            refine ⟨by simpa using hsupp, Nat.mod_lt _ (by norm_num), by simp, ?_⟩
            have step₁ : Equivalent n m (g :: gs)
                ([g] ++ ((r'.before ++ r'.after) ++ (diagRun r'.k q ++ Gate.h q :: r'.rest))) := by
              have := Equivalent.append_left (n := n) (m := m) [g] hequiv
              simpa [List.append_assoc] using this
            have step₂ : Equivalent n m
                ([g] ++ ((r'.before ++ r'.after) ++ (diagRun r'.k q ++ Gate.h q :: r'.rest)))
                ((r'.before ++ r'.after) ++ ([g] ++ (diagRun r'.k q ++ Gate.h q :: r'.rest))) := by
              have hcomm := Equivalent.append_comm (n := n) (m := m) [g] (r'.before ++ r'.after)
                (fun g' hg' => by rcases List.mem_singleton.mp hg' with rfl; exact hw.isUnitary)
                (fun g' hg' g'' hg'' => by
                  rcases List.mem_singleton.mp hg' with rfl
                  exact disjoint_of_onWire hw (hsupp g'' hg''))
              have := Equivalent.append_right (n := n) (m := m)
                (diagRun r'.k q ++ Gate.h q :: r'.rest) hcomm
              simpa [List.append_assoc] using this
            have step₃ : Equivalent n m
                ((r'.before ++ r'.after) ++ ([g] ++ (diagRun r'.k q ++ Gate.h q :: r'.rest)))
                ((r'.before ++ r'.after) ++ (diagRun ((kg + r'.k) % 8) q ++
                  Gate.h q :: r'.rest)) := by
              refine Equivalent.append_left _ ?_
              have hmerge : Equivalent n m ([g] ++ diagRun r'.k q)
                  (diagRun ((kg + r'.k) % 8) q) :=
                Equivalent.trans
                  (Equivalent.append_right _ (Equivalent.diagonal_gate hd))
                  (Equivalent.diagRun_append kg r'.k q hkg8 hk8)
              have := Equivalent.append_right (n := n) (m := m) (Gate.h q :: r'.rest) hmerge
              simpa [List.append_assoc] using this
            simpa using Equivalent.trans step₁ (Equivalent.trans step₂ step₃)
      · rw [if_neg hs] at h
        simp only [Option.map_eq_some_iff] at h
        obtain ⟨r', hscan, rfl⟩ := h
        obtain ⟨hsupp, hk8, hnorun, hequiv⟩ := ih hscan
        by_cases hrun : r'.hasRun = true
        · rw [HScan.push_of_hasRun hrun]
          refine ⟨?_, hk8, fun hc => absurd (hc ▸ hrun) (by simp), ?_⟩
          · intro x hx
            simp only [List.cons_append, List.mem_cons] at hx
            rcases hx with rfl | hx
            · simpa using hs
            · exact hsupp x hx
          · have := Equivalent.append_left (n := n) (m := m) [g] hequiv
            simpa [List.append_assoc] using this
        · simp only [Bool.not_eq_true] at hrun
          rw [HScan.push_of_not_hasRun hrun]
          have hbefore : r'.before = [] := hnorun hrun
          refine ⟨?_, hk8, fun _ => hbefore, ?_⟩
          · intro x hx
            rw [hbefore] at hx
            simp only [List.nil_append, List.mem_cons] at hx
            rcases hx with rfl | hx
            · simpa using hs
            · exact hsupp x (by simp [hbefore, hx])
          · have := Equivalent.append_left (n := n) (m := m) [g] hequiv
            rw [hbefore] at this ⊢
            simpa [List.append_assoc] using this

/-! ### Sweep 2 is semantics preserving -/

/-- Gates confined to one wire may be gathered past gates that miss it. -/
theorem Equivalent.gather {n m : Nat} {q : Qubit} (A B C : List Gate)
    (hA : ∀ g ∈ A, OnWire q g) (hB : ∀ g ∈ B, g.support q = false) :
    Equivalent n m (A ++ B ++ C) (B ++ A ++ C) := by
  have h := Equivalent.append_comm (n := n) (m := m) A B
    (fun g hg => (hA g hg).isUnitary)
    (fun g hg g' hg' => disjoint_of_onWire (hA g hg) (hB g' hg'))
  simpa using Equivalent.append_right C h

private theorem onWire_h {q : Qubit} : OnWire q (Gate.h q) := rfl

/-- The opening `h` reaches the run: the window becomes `H · run · H` followed by the
untouched gates. -/
private theorem hwindow {n m : Nat} {q : Qubit} (before after rest : List Gate) (k : Nat)
    (hb : ∀ g ∈ before ++ after, g.support q = false) :
    Equivalent n m (Gate.h q :: (before ++ after ++ (diagRun k q ++ Gate.h q :: rest)))
      ((before ++ after) ++ (([Gate.h q] ++ diagRun k q ++ [Gate.h q]) ++ rest)) := by
  have h := Equivalent.gather (n := n) (m := m) [Gate.h q] (before ++ after)
    (diagRun k q ++ Gate.h q :: rest) (fun g hg => by
      rcases List.mem_singleton.mp hg with rfl; exact onWire_h) hb
  simpa [List.append_assoc] using h

/-- The replacement gates, emitted where the run started, may equally be gathered: `A` sits
where the opening `h` was, `B` where the run's first gate was, and `C` where the closing `h`
was. -/
private theorem out_gather {n m : Nat} {q : Qubit} (before after rest A B C : List Gate)
    (hA : ∀ g ∈ A, OnWire q g) (hB : ∀ g ∈ B, OnWire q g) (_hC : ∀ g ∈ C, OnWire q g)
    (hb : ∀ g ∈ before, g.support q = false) (ha : ∀ g ∈ after, g.support q = false) :
    Equivalent n m (A ++ before ++ (B ++ after ++ (C ++ rest)))
      ((before ++ after) ++ ((A ++ B ++ C) ++ rest)) := by
  have hAB : ∀ g ∈ A ++ B, OnWire q g := by
    intro g hg
    rcases List.mem_append.mp hg with hg | hg
    · exact hA g hg
    · exact hB g hg
  have h₁ : Equivalent n m (A ++ before ++ (B ++ after ++ (C ++ rest)))
      (before ++ A ++ (B ++ after ++ (C ++ rest))) :=
    Equivalent.gather A before _ hA hb
  have h₂ : Equivalent n m ((A ++ B) ++ after ++ (C ++ rest))
      (after ++ (A ++ B) ++ (C ++ rest)) :=
    Equivalent.gather (A ++ B) after _ hAB ha
  refine Equivalent.trans h₁ ?_
  have h₃ := Equivalent.append_left (n := n) (m := m) before h₂
  simpa [List.append_assoc] using h₃

/-- **Every Hadamard rewrite is semantics preserving.** -/
theorem reduceAtH_correct {n m : Nat} {q : Qubit} {gs out : List Gate}
    (h : reduceAtH q gs = some out) : Equivalent n m (Gate.h q :: gs) out := by
  unfold reduceAtH at h
  rcases hx : scanXH q gs with _ | ⟨b₁, b₂, rest⟩
  · -- no `H·X·H`; the diagonal-run rules
    rw [hx] at h
    dsimp only at h
    rcases hscan : scanH q gs with _ | r
    · rw [hscan] at h; simp at h
    · rw [hscan] at h
      dsimp only at h
      obtain ⟨hsupp, hk8, -, hequiv⟩ := scanH_spec (n := n) (m := m) hscan
      have hb : ∀ g ∈ r.before, g.support q = false := fun g hg => hsupp g (by simp [hg])
      have ha : ∀ g ∈ r.after, g.support q = false := fun g hg => hsupp g (by simp [hg])
      have hstart : Equivalent n m (Gate.h q :: gs)
          ((r.before ++ r.after) ++
            (([Gate.h q] ++ diagRun r.k q ++ [Gate.h q]) ++ r.rest)) := by
        refine Equivalent.trans (Equivalent.append_left [Gate.h q] hequiv) ?_
        simpa [List.append_assoc] using hwindow r.before r.after r.rest r.k hsupp
      by_cases hodd : r.k % 2 = 1
      · rw [if_pos hodd] at h; simp at h
      · rw [if_neg hodd] at h
        have hk : r.k = 0 ∨ r.k = 2 ∨ r.k = 4 ∨ r.k = 6 := by omega
        rcases hk with hk | hk | hk | hk
        · rw [if_pos hk] at h
          simp only [Option.some.injEq] at h
          subst h
          refine Equivalent.trans hstart ?_
          rw [hk]
          have hrule : Equivalent n m ([Gate.h q] ++ diagRun 0 q ++ [Gate.h q]) [] := by
            simpa [diagRun] using Equivalent.hh (n := n) (m := m) q
          have := Equivalent.append_left (r.before ++ r.after)
            (Equivalent.append_right r.rest hrule)
          simpa [List.append_assoc] using this
        · rw [if_neg (by omega : ¬ r.k = 0), if_neg (by omega : ¬ r.k = 4), if_pos hk] at h
          simp only [Option.some.injEq] at h
          subst h
          refine Equivalent.trans hstart ?_
          rw [hk]
          have hrule : Equivalent n m ([Gate.h q] ++ diagRun 2 q ++ [Gate.h q])
              [Gate.sdg q, Gate.h q, Gate.sdg q] := by
            simpa [diagRun] using Equivalent.hsh (n := n) (m := m) q
          have hleft := Equivalent.append_left (r.before ++ r.after)
            (Equivalent.append_right r.rest hrule)
          refine Equivalent.trans (by simpa [List.append_assoc] using hleft) ?_
          have := out_gather (n := n) (m := m) (q := q) r.before r.after r.rest
            [Gate.sdg q] [Gate.h q] [Gate.sdg q]
            (fun g hg => by rcases List.mem_singleton.mp hg with rfl; rfl)
            (fun g hg => by rcases List.mem_singleton.mp hg with rfl; rfl)
            (fun g hg => by rcases List.mem_singleton.mp hg with rfl; rfl) hb ha
          simpa [List.append_assoc] using this.symm
        · rw [if_neg (by omega : ¬ r.k = 0), if_pos hk] at h
          simp only [Option.some.injEq] at h
          subst h
          refine Equivalent.trans hstart ?_
          rw [hk]
          have hrule : Equivalent n m ([Gate.h q] ++ diagRun 4 q ++ [Gate.h q]) [Gate.x q] := by
            simpa [diagRun] using Equivalent.hzh (n := n) (m := m) q
          have hleft := Equivalent.append_left (r.before ++ r.after)
            (Equivalent.append_right r.rest hrule)
          refine Equivalent.trans (by simpa [List.append_assoc] using hleft) ?_
          have := out_gather (n := n) (m := m) (q := q) r.before r.after r.rest
            [] [Gate.x q] [] (by simp)
            (fun g hg => by rcases List.mem_singleton.mp hg with rfl; rfl)
            (by simp) hb ha
          simpa [List.append_assoc] using this.symm
        · rw [if_neg (by omega : ¬ r.k = 0), if_neg (by omega : ¬ r.k = 4),
            if_neg (by omega : ¬ r.k = 2)] at h
          simp only [Option.some.injEq] at h
          subst h
          refine Equivalent.trans hstart ?_
          rw [hk]
          have hrule : Equivalent n m ([Gate.h q] ++ diagRun 6 q ++ [Gate.h q])
              [Gate.s q, Gate.h q, Gate.s q] := by
            simpa [diagRun] using Equivalent.hsdgh (n := n) (m := m) q
          have hleft := Equivalent.append_left (r.before ++ r.after)
            (Equivalent.append_right r.rest hrule)
          refine Equivalent.trans (by simpa [List.append_assoc] using hleft) ?_
          have := out_gather (n := n) (m := m) (q := q) r.before r.after r.rest
            [Gate.s q] [Gate.h q] [Gate.s q]
            (fun g hg => by rcases List.mem_singleton.mp hg with rfl; rfl)
            (fun g hg => by rcases List.mem_singleton.mp hg with rfl; rfl)
            (fun g hg => by rcases List.mem_singleton.mp hg with rfl; rfl) hb ha
          simpa [List.append_assoc] using this.symm
  · -- the `H·X·H = Z` rule
    rw [hx] at h
    dsimp only at h
    simp only [Option.some.injEq] at h
    subst h
    obtain ⟨hgs, h1, h2⟩ := scanXH_spec hx
    subst hgs
    have hstep : Equivalent n m
        (Gate.h q :: (b₁ ++ Gate.x q :: (b₂ ++ Gate.h q :: rest)))
        ((b₁ ++ b₂) ++ ([Gate.h q, Gate.x q, Gate.h q] ++ rest)) := by
      have g₁ : Equivalent n m (Gate.h q :: (b₁ ++ Gate.x q :: (b₂ ++ Gate.h q :: rest)))
          (b₁ ++ (Gate.h q :: Gate.x q :: (b₂ ++ Gate.h q :: rest))) := by
        have := Equivalent.gather (n := n) (m := m) [Gate.h q] b₁
          (Gate.x q :: (b₂ ++ Gate.h q :: rest))
          (fun g hg => by rcases List.mem_singleton.mp hg with rfl; exact onWire_h) h1
        simpa using this
      have g₂ : Equivalent n m ([Gate.h q, Gate.x q] ++ (b₂ ++ (Gate.h q :: rest)))
          (b₂ ++ ([Gate.h q, Gate.x q] ++ (Gate.h q :: rest))) := by
        have := Equivalent.gather (n := n) (m := m) [Gate.h q, Gate.x q] b₂
          (Gate.h q :: rest) (fun g hg => by fin_cases hg <;> rfl) h2
        simpa [List.append_assoc] using this
      refine Equivalent.trans g₁ ?_
      have := Equivalent.append_left (n := n) (m := m) b₁ g₂
      simpa [List.append_assoc] using this
    refine Equivalent.trans hstep ?_
    have hrule := Equivalent.append_left (n := n) (m := m) (b₁ ++ b₂)
      (Equivalent.append_right rest (Equivalent.hxh (n := n) (m := m) q))
    refine Equivalent.trans (by simpa [List.append_assoc] using hrule) ?_
    have := out_gather (n := n) (m := m) (q := q) b₁ b₂ rest [] [Gate.z q] [] (by simp)
      (fun g hg => by rcases List.mem_singleton.mp hg with rfl; rfl) (by simp) h1 h2
    simpa [List.append_assoc] using this.symm

/-- One sweep of Hadamard reduction preserves semantics. -/
theorem reduceStep_correct {n m : Nat} : ∀ {gs out : List Gate}, reduceStep gs = some out →
    Equivalent n m out gs := by
  intro gs
  induction gs with
  | nil => intro out h; simp [reduceStep] at h
  | cons g gs ih =>
      intro out h
      simp only [reduceStep] at h
      cases hg : g with
      | h q =>
          subst hg
          dsimp only at h
          rcases hred : reduceAtH q gs with _ | out'
          · rw [hred] at h
            dsimp only at h
            simp only [Option.map_eq_some_iff] at h
            obtain ⟨out'', hstep, rfl⟩ := h
            simpa using Equivalent.append_left (n := n) (m := m) [Gate.h q] (ih hstep)
          · rw [hred] at h
            dsimp only at h
            simp only [Option.some.injEq] at h
            subst h
            exact (reduceAtH_correct hred).symm
      | _ =>
          subst hg
          dsimp only at h
          simp only [Option.map_eq_some_iff] at h
          obtain ⟨out'', hstep, rfl⟩ := h
          simpa using Equivalent.append_left (n := n) (m := m) [_] (ih hstep)

/-- Iterating the sweep preserves semantics. -/
theorem reduceHadamardsFuel_correct {n m : Nat} (fuel : Nat) (gs : List Gate) :
    Equivalent n m (reduceHadamardsFuel fuel gs) gs := by
  induction fuel generalizing gs with
  | zero => exact Equivalent.refl _ _ _
  | succ fuel ih =>
      rw [reduceHadamardsFuel]
      rcases hstep : reduceStep gs with _ | gs'
      · exact Equivalent.refl _ _ _
      · exact Equivalent.trans (ih gs') (reduceStep_correct hstep)

/-- **Sweep 2 is semantics preserving.** -/
theorem reduceHadamards_correct {n m : Nat} (gs : List Gate) :
    Equivalent n m (reduceHadamards gs) gs :=
  reduceHadamardsFuel_correct _ gs

/-! ## Sweep 3: `CNOT`/`CZ` pairs across commuting gates

The Rust `cancel_commuting_pairs` walks forward from each two-qubit gate through everything
that commutes with it, looking for its twin. The commutation tables are `commutes_past_cnot`
and `commutes_past_cz`, ported verbatim below and then *proved* — each entry is a real
algebraic identity (`X` on the target of a `CNOT`, a diagonal on its control, a `CNOT`
sharing a control, …), not a disjointness argument.
-/

/-- The Rust `commutes_past_cnot`: `g` commutes with `CNOT(c, t)`. -/
def commutesPastCnot (g : Gate) (c t : Qubit) : Bool :=
  match g with
  | .x q => q != c
  | .h q => q != c && q != t
  | .s q | .sdg q | .z q | .t q | .tdg q | .rz _ q => q != t
  | .cnot c₂ t₂ => c₂ != t && t₂ != c
  | .cz a b => a != t && b != t
  | .ccx c₁ c₂ tgt =>
      c₁ != c && c₁ != t && c₂ != c && c₂ != t && tgt != c && tgt != t
  | .ccz c₁ c₂ tgt => tgt != t && c₁ != t && c₂ != t
  | .measure q _ => q != c && q != t
  | .reset q => q != c && q != t

/-- The Rust `commutes_past_cz`: `g` commutes with `CZ(a, b)`. -/
def commutesPastCz (g : Gate) (a b : Qubit) : Bool :=
  match g with
  | .x q | .h q => q != a && q != b
  | .s _ | .sdg _ | .z _ | .t _ | .tdg _ | .rz _ _ | .cz .. | .ccz .. => true
  | .cnot _ tgt | .ccx _ _ tgt => tgt != a && tgt != b
  | .measure q _ => q != a && q != b
  | .reset q => q != a && q != b

/-- `g` commutes with the two-qubit gate `p`. -/
def pairCommutes : Gate → Gate → Bool
  | .cnot c t, g => commutesPastCnot g c t
  | .cz a b, g => commutesPastCz g a b
  | _, _ => false

/-- Is this a gate sweep 3 tries to cancel? -/
def isPair : Gate → Bool
  | .cnot .. | .cz .. => true
  | _ => false

/-- Look ahead for `p`'s twin, through gates that commute with it. -/
def findPartner (p : Gate) : List Gate → Option (List Gate)
  | [] => none
  | g :: gs =>
      if gatesEqual p g then some gs
      else if pairCommutes p g then (findPartner p gs).map (g :: ·)
      else none

/-- One cancellation anywhere in the list, or `none` at the fixpoint. -/
def cancelCommutingStep : List Gate → Option (List Gate)
  | [] => none
  | g :: gs =>
      if isPair g then
        match findPartner g gs with
        | some gs' => some gs'
        | none => (cancelCommutingStep gs).map (g :: ·)
      else (cancelCommutingStep gs).map (g :: ·)

/-- Iterate; each firing deletes two gates, so `gs.length` steps suffice. -/
def cancelCommutingFuel : Nat → List Gate → List Gate
  | 0, gs => gs
  | fuel + 1, gs =>
      match cancelCommutingStep gs with
      | some gs' => cancelCommutingFuel fuel gs'
      | none => gs

/-- Cancel matching `CNOT`/`CZ` pairs across gates they commute with. -/
def cancelCommutingPairs (gs : List Gate) : List Gate := cancelCommutingFuel gs.length gs

/-! ### The commutation table, proved -/

/-- Diagonal gates, as the tables classify them. -/
def IsDiagGate : Gate → Bool
  | .s _ | .sdg _ | .z _ | .t _ | .tdg _ | .rz _ _ | .cz .. | .ccz .. => true
  | _ => false

theorem embed1_diag2_eq_phaseMatrix {n : Nat} (a b : ℂ) (q : Qubit) (hq : q < n) :
    embed1 n (diag2 a b) q = phaseMatrix (fun s : Basis n => if s.get q then b else a) := by
  funext out inp
  simp only [embed1_apply_of_lt _ hq, phaseMatrix, diag2]
  by_cases h : out = inp
  · subst h
    have hall : ∀ r : Fin n, (r : Nat) ≠ q → out r = out r := fun _ _ => rfl
    rw [if_pos hall, if_pos rfl]
    simp [Basis.get, hq]
  · rw [if_neg h]
    by_cases hall : ∀ r : Fin n, (r : Nat) ≠ q → out r = inp r
    · rw [if_pos hall]
      have hne : out ⟨q, hq⟩ ≠ inp ⟨q, hq⟩ := by
        intro hc
        refine h (funext fun r => ?_)
        by_cases hr : (r : Nat) = q
        · have : r = ⟨q, hq⟩ := Fin.ext hr
          rw [this]; exact hc
        · exact hall r hr
      simp [hne]
    · rw [if_neg hall]

/-- Every diagonal gate is a phase matrix whose phase reads only the gate's own wires. -/
theorem exists_phase_of_isDiagGate {n : Nat} {g : Gate} (h : IsDiagGate g = true) :
    ∃ f : Basis n → ℂ, gateUnitary n g = phaseMatrix f ∧
      ∀ b b' : Basis n, (∀ q ∈ g.qubitsOf, b.get q = b'.get q) → f b = f b' := by
  have one_case : ∀ q : Qubit, ¬ q < n → ∀ (a b : ℂ),
      ∃ f : Basis n → ℂ, embed1 n (diag2 a b) q = phaseMatrix f ∧
        ∀ b₁ b₂ : Basis n, (∀ r ∈ [q], b₁.get r = b₂.get r) → f b₁ = f b₂ := by
    intro q hq a b
    exact ⟨fun _ => 1, by rw [embed1_eq_one _ hq, phaseMatrix_one], fun _ _ _ => rfl⟩
  have wire_case : ∀ (q : Qubit) (a b : ℂ),
      ∃ f : Basis n → ℂ, embed1 n (diag2 a b) q = phaseMatrix f ∧
        ∀ b₁ b₂ : Basis n, (∀ r ∈ [q], b₁.get r = b₂.get r) → f b₁ = f b₂ := by
    intro q a b
    by_cases hq : q < n
    · exact ⟨fun s => if s.get q then b else a, embed1_diag2_eq_phaseMatrix a b q hq,
        fun b₁ b₂ hb => by simp only [hb q (by simp)]⟩
    · exact one_case q hq a b
  cases g with
  | s q => exact wire_case q 1 (ep (1/2))
  | sdg q => exact wire_case q 1 (ep (-1/2))
  | z q => exact wire_case q 1 (ep 1)
  | t q => exact wire_case q 1 (ep (1/4))
  | tdg q => exact wire_case q 1 (ep (-1/4))
  | rz θ q => exact wire_case q (ep (-θ/2)) (ep (θ/2))
  | cz a b =>
      refine ⟨_, rfl, fun b₁ b₂ hb => ?_⟩
      simp only [hb a (by simp [Gate.qubitsOf]), hb b (by simp [Gate.qubitsOf])]
  | ccz a b c =>
      refine ⟨_, rfl, fun b₁ b₂ hb => ?_⟩
      simp only [hb a (by simp [Gate.qubitsOf]), hb b (by simp [Gate.qubitsOf]),
        hb c (by simp [Gate.qubitsOf])]
  | _ => simp [IsDiagGate] at h

/-- A `CNOT` commutes with any diagonal gate that does not read its target. -/
theorem comm_cnot_diag {n : Nat} {g : Gate} (c t : Qubit) (hd : IsDiagGate g = true)
    (hq : ∀ q ∈ g.qubitsOf, q ≠ t) :
    gateUnitary n (.cnot c t) * gateUnitary n g = gateUnitary n g * gateUnitary n (.cnot c t) := by
  obtain ⟨f, hf, hdep⟩ := exists_phase_of_isDiagGate (n := n) hd
  rw [hf, gateUnitary]
  exact comm_perm_phase _ _ fun b => hdep _ _ fun q hq' => by
    simp [Basis.get_set_ne _ _ _ _ (hq q hq')]

/-- A `CCX` commutes with any diagonal gate that does not read its target. -/
theorem comm_ccx_diag {n : Nat} {g : Gate} (c₁ c₂ t : Qubit) (hd : IsDiagGate g = true)
    (hq : ∀ q ∈ g.qubitsOf, q ≠ t) :
    gateUnitary n (.ccx c₁ c₂ t) * gateUnitary n g =
      gateUnitary n g * gateUnitary n (.ccx c₁ c₂ t) := by
  obtain ⟨f, hf, hdep⟩ := exists_phase_of_isDiagGate (n := n) hd
  rw [hf, gateUnitary]
  exact comm_perm_phase _ _ fun b => hdep _ _ fun q hq' => by
    simp [Basis.get_set_ne _ _ _ _ (hq q hq')]

/-- Gates with no operand in common have disjoint supports. -/
theorem disjoint_support_of {g g' : Gate}
    (h : ∀ q ∈ g.qubitsOf, ∀ q' ∈ g'.qubitsOf, q ≠ q') :
    Wires.Disjoint g.support g'.support := by
  intro r hr
  by_contra hc
  simp only [Bool.not_eq_false] at hc
  exact h r ((Gate.support_iff g r).mp hr) r ((Gate.support_iff g' r).mp hc) rfl

/-- `X` commutes past a `CNOT` unless it sits on the control. -/
theorem cnot_x_comm {n : Nat} (c t q : Qubit) (hqc : q ≠ c) :
    (fun b : Basis n => b.set t (b.get t != b.get c)) ∘ (fun b : Basis n => b.set q (!b.get q))
      = (fun b : Basis n => b.set q (!b.get q)) ∘
        (fun b : Basis n => b.set t (b.get t != b.get c)) := by
  funext b
  simp only [Function.comp_apply]
  by_cases hqt : q = t
  · subst hqt
    by_cases hqn : q < n
    · rw [Basis.get_set_same _ _ _ hqn, Basis.get_set_ne _ _ _ _ (Ne.symm hqc),
        Basis.set_set, Basis.get_set_same _ _ _ hqn, Basis.set_set]
      congr 1
      cases b.get q <;> cases b.get c <;> rfl
    · simp [Basis.set_out_of_range _ _ _ hqn]
  · rw [Basis.get_set_ne _ _ _ _ (Ne.symm hqt), Basis.get_set_ne _ _ _ _ (Ne.symm hqc),
      Basis.get_set_ne _ _ _ _ hqt, Basis.set_comm _ (Ne.symm hqt)]

/-- Two `CNOT`s commute when neither's control is the other's target. -/
theorem cnot_cnot_comm {n : Nat} (c t c₂ t₂ : Qubit) (h1 : c₂ ≠ t) (h2 : t₂ ≠ c) :
    (fun b : Basis n => b.set t (b.get t != b.get c)) ∘
        (fun b : Basis n => b.set t₂ (b.get t₂ != b.get c₂))
      = (fun b : Basis n => b.set t₂ (b.get t₂ != b.get c₂)) ∘
        (fun b : Basis n => b.set t (b.get t != b.get c)) := by
  funext b
  simp only [Function.comp_apply]
  by_cases htt : t = t₂
  · subst htt
    by_cases htn : t < n
    · rw [Basis.get_set_same _ _ _ htn, Basis.get_set_ne _ _ _ _ (Ne.symm h2),
        Basis.set_set, Basis.get_set_same _ _ _ htn, Basis.get_set_ne _ _ _ _ h1,
        Basis.set_set]
      congr 1
      cases b.get t <;> cases b.get c <;> cases b.get c₂ <;> rfl
    · simp [Basis.set_out_of_range _ _ _ htn]
  · rw [Basis.get_set_ne _ _ _ _ (Ne.symm htt), Basis.get_set_ne _ _ _ _ (Ne.symm h2),
      Basis.get_set_ne _ _ _ _ htt, Basis.get_set_ne _ _ _ _ h1,
      Basis.set_comm _ (Ne.symm htt)]

/-- **Every entry of the `CNOT` commutation table is a real identity.** -/
theorem gateUnitary_comm_commutesPastCnot {n : Nat} {g : Gate} {c t : Qubit}
    (hgu : g.isUnitary = true) (h : commutesPastCnot g c t = true) :
    gateUnitary n (.cnot c t) * gateUnitary n g =
      gateUnitary n g * gateUnitary n (.cnot c t) := by
  cases g with
  | x q =>
      have hqc : q ≠ c := by simpa [commutesPastCnot] using h
      rw [gateUnitary, gateUnitary, embed1_x2_eq_perm, permMatrix_mul, permMatrix_mul,
        cnot_x_comm c t q hqc]
  | h q =>
      simp only [commutesPastCnot, Bool.and_eq_true, bne_iff_ne, ne_eq] at h
      refine SupportedOn.mul_comm (gateUnitary_supportedOn n _) (gateUnitary_supportedOn n _) ?_
      refine disjoint_support_of fun q' hq' q'' hq'' => ?_
      simp only [Gate.qubitsOf, List.mem_cons, List.not_mem_nil,
        or_false] at hq' hq''
      rcases hq' with rfl | rfl <;> subst hq'' <;> simp_all <;> tauto
  | s q | sdg q | z q | t q | tdg q | rz _ q =>
      refine comm_cnot_diag c t rfl fun q' hq' => ?_
      simp only [Gate.qubitsOf, List.mem_singleton] at hq'
      subst hq'
      simpa [commutesPastCnot] using h
  | cnot c₂ t₂ =>
      simp only [commutesPastCnot, Bool.and_eq_true, bne_iff_ne, ne_eq] at h
      rw [gateUnitary, gateUnitary, permMatrix_mul, permMatrix_mul,
        cnot_cnot_comm c t c₂ t₂ h.1 h.2]
  | cz a b =>
      refine comm_cnot_diag c t rfl fun q' hq' => ?_
      simp only [commutesPastCnot, Bool.and_eq_true, bne_iff_ne, ne_eq] at h
      simp only [Gate.qubitsOf, List.mem_cons, List.not_mem_nil,
        or_false] at hq'
      rcases hq' with rfl | rfl
      · exact h.1
      · exact h.2
  | ccx c₁ c₂ tgt =>
      simp only [commutesPastCnot, Bool.and_eq_true, bne_iff_ne, ne_eq] at h
      refine SupportedOn.mul_comm (gateUnitary_supportedOn n _) (gateUnitary_supportedOn n _) ?_
      refine disjoint_support_of fun q' hq' q'' hq'' => ?_
      simp only [Gate.qubitsOf, List.mem_cons, List.not_mem_nil,
        or_false] at hq' hq''
      obtain ⟨⟨⟨⟨⟨ha, hb⟩, hc⟩, hd⟩, he⟩, hf⟩ := h
      rcases hq' with rfl | rfl <;> rcases hq'' with rfl | rfl | rfl <;>
        first
          | exact fun hc' => ha hc'.symm
          | exact fun hc' => hb hc'.symm
          | exact fun hc' => hc hc'.symm
          | exact fun hc' => hd hc'.symm
          | exact fun hc' => he hc'.symm
          | exact fun hc' => hf hc'.symm
  | ccz c₁ c₂ tgt =>
      refine comm_cnot_diag c t rfl fun q' hq' => ?_
      simp only [commutesPastCnot, Bool.and_eq_true, bne_iff_ne, ne_eq] at h
      simp only [Gate.qubitsOf, List.mem_cons, List.not_mem_nil,
        or_false] at hq'
      rcases hq' with rfl | rfl | rfl
      · exact h.1.2
      · exact h.2
      · exact h.1.1
  | measure q c' => simp [Gate.isUnitary, Gate.isMeasurement] at hgu
  | reset q => simp [Gate.isUnitary, Gate.isMeasurement] at hgu

/-- **Every entry of the `CZ` commutation table is a real identity.** -/
theorem gateUnitary_comm_commutesPastCz {n : Nat} {g : Gate} {a b : Qubit}
    (hgu : g.isUnitary = true) (h : commutesPastCz g a b = true) :
    gateUnitary n (.cz a b) * gateUnitary n g =
      gateUnitary n g * gateUnitary n (.cz a b) := by
  have hdiag : IsDiagonal (gateUnitary n (.cz a b)) := isDiagonal_phaseMatrix _
  cases g with
  | x q | h q =>
      simp only [commutesPastCz, Bool.and_eq_true, bne_iff_ne, ne_eq] at h
      refine SupportedOn.mul_comm (gateUnitary_supportedOn n _) (gateUnitary_supportedOn n _) ?_
      refine disjoint_support_of fun q' hq' q'' hq'' => ?_
      simp only [Gate.qubitsOf, List.mem_cons, List.not_mem_nil,
        or_false] at hq' hq''
      subst hq''
      rcases hq' with rfl | rfl
      · exact fun hc => h.1 hc.symm
      · exact fun hc => h.2 hc.symm
  | s q | sdg q | z q | t q | tdg q | rz _ q =>
      exact hdiag.mul_comm (isDiagonal_embed1_diag2 _ _ _)
  | cz a' b' => exact hdiag.mul_comm (isDiagonal_phaseMatrix _)
  | ccz c₁ c₂ tgt => exact hdiag.mul_comm (isDiagonal_phaseMatrix _)
  | cnot c₂ tgt =>
      simp only [commutesPastCz, Bool.and_eq_true, bne_iff_ne, ne_eq] at h
      refine (comm_cnot_diag (n := n) c₂ tgt rfl fun q' hq' => ?_).symm
      simp only [Gate.qubitsOf, List.mem_cons, List.not_mem_nil,
        or_false] at hq'
      rcases hq' with rfl | rfl
      · exact fun hc => h.1 hc.symm
      · exact fun hc => h.2 hc.symm
  | ccx c₁ c₂ tgt =>
      simp only [commutesPastCz, Bool.and_eq_true, bne_iff_ne, ne_eq] at h
      refine (comm_ccx_diag (n := n) c₁ c₂ tgt rfl fun q' hq' => ?_).symm
      simp only [Gate.qubitsOf, List.mem_cons, List.not_mem_nil,
        or_false] at hq'
      rcases hq' with rfl | rfl
      · exact fun hc => h.1 hc.symm
      · exact fun hc => h.2 hc.symm
  | measure q c' => simp [Gate.isUnitary, Gate.isMeasurement] at hgu
  | reset q => simp [Gate.isUnitary, Gate.isMeasurement] at hgu

/-- Matching gates are self-inverse (the relation only holds between the seven kinds). -/
theorem isSelfInverse_of_gatesEqual {p g : Gate} (h : gatesEqual p g = true) :
    g.isSelfInverse = true := by
  cases p <;> cases g <;> first | exact Bool.noConfusion h | rfl

/-- Matching gates inherit well-formedness. -/
theorem Wf_of_gatesEqual {p g : Gate} (h : gatesEqual p g = true) (hwf : p.Wf) : g.Wf := by
  cases p <;> cases g <;> first | exact Bool.noConfusion h | trivial | skip
  case cnot.cnot c t c' t' =>
    simp only [gatesEqual, Bool.and_eq_true, beq_iff_eq] at h
    obtain ⟨rfl, rfl⟩ := h
    exact hwf
  case cz.cz a b a' b' =>
    have hab : a ≠ b := hwf
    simp only [gatesEqual, Bool.and_eq_true, Bool.or_eq_true, beq_iff_eq] at h
    rcases h with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
    · exact hab
    · exact hab.symm
  case ccx.ccx a b c a' b' c' =>
    simp only [gatesEqual, Bool.and_eq_true, beq_iff_eq] at h
    obtain ⟨⟨rfl, rfl⟩, rfl⟩ := h
    exact hwf
  case ccz.ccz a b c a' b' c' =>
    obtain ⟨h1, h2, h3⟩ := hwf
    simp only [gatesEqual, Bool.and_eq_true, Bool.or_eq_true, beq_iff_eq] at h
    rcases h with ((((⟨⟨rfl, rfl⟩, rfl⟩ | ⟨⟨rfl, rfl⟩, rfl⟩) | ⟨⟨rfl, rfl⟩, rfl⟩) |
        ⟨⟨rfl, rfl⟩, rfl⟩) | ⟨⟨rfl, rfl⟩, rfl⟩) | ⟨⟨rfl, rfl⟩, rfl⟩
    · exact ⟨h1, h2, h3⟩
    · exact ⟨h2, h1, h3.symm⟩
    · exact ⟨h1.symm, h3, h2⟩
    · exact ⟨h2.symm, h3.symm, h1⟩
    · exact ⟨h3, h1.symm, h2.symm⟩
    · exact ⟨h3.symm, h2.symm, h1.symm⟩

/-- **The commutation table is sound**: a listed gate really does commute with the pair. -/
theorem Equivalent.pairCommutes_swap {n m : Nat} {p g : Gate} (hp : isPair p = true)
    (h : pairCommutes p g = true) : Equivalent n m [p, g] [g, p] := by
  have hpu : p.isUnitary = true := by
    cases p <;> first | rfl | exact Bool.noConfusion hp
  by_cases hgu : g.isUnitary = true
  · have hcomm : gateUnitary n p * gateUnitary n g = gateUnitary n g * gateUnitary n p := by
      cases p with
      | cnot c t => exact gateUnitary_comm_commutesPastCnot hgu (by simpa [pairCommutes] using h)
      | cz a b => exact gateUnitary_comm_commutesPastCz hgu (by simpa [pairCommutes] using h)
      | _ => exact Bool.noConfusion hp
    intro ρ
    simp only [denote_cons, denote_nil]
    exact step_comm_unitary hpu hgu hcomm ρ
  · -- `measure` / `reset`: the table only lets the pair past on disjoint wires
    refine Equivalent.swap_of_disjoint hpu (disjoint_support_of fun q hq q' hq' => ?_)
    cases p with
    | cnot c t =>
        simp only [pairCommutes] at h
        cases g with
        | measure qm cm =>
            simp only [commutesPastCnot, Bool.and_eq_true, bne_iff_ne, ne_eq] at h
            simp only [Gate.qubitsOf, List.mem_cons, List.not_mem_nil,
              or_false] at hq hq'
            subst hq'
            rcases hq with rfl | rfl
            · exact fun hc => h.1 hc.symm
            · exact fun hc => h.2 hc.symm
        | reset qr =>
            simp only [commutesPastCnot, Bool.and_eq_true, bne_iff_ne, ne_eq] at h
            simp only [Gate.qubitsOf, List.mem_cons, List.not_mem_nil,
              or_false] at hq hq'
            subst hq'
            rcases hq with rfl | rfl
            · exact fun hc => h.1 hc.symm
            · exact fun hc => h.2 hc.symm
        | _ => exact absurd rfl hgu
    | cz a b =>
        simp only [pairCommutes] at h
        cases g with
        | measure qm cm =>
            simp only [commutesPastCz, Bool.and_eq_true, bne_iff_ne, ne_eq] at h
            simp only [Gate.qubitsOf, List.mem_cons, List.not_mem_nil,
              or_false] at hq hq'
            subst hq'
            rcases hq with rfl | rfl
            · exact fun hc => h.1 hc.symm
            · exact fun hc => h.2 hc.symm
        | reset qr =>
            simp only [commutesPastCz, Bool.and_eq_true, bne_iff_ne, ne_eq] at h
            simp only [Gate.qubitsOf, List.mem_cons, List.not_mem_nil,
              or_false] at hq hq'
            subst hq'
            rcases hq with rfl | rfl
            · exact fun hc => h.1 hc.symm
            · exact fun hc => h.2 hc.symm
        | _ => exact absurd rfl hgu
    | _ => exact Bool.noConfusion hp

/-- The lookahead is semantics preserving: the pair reaches its twin and both vanish. -/
theorem findPartner_correct {n m : Nat} {p : Gate} (hp : isPair p = true) (hwf : p.Wf) :
    ∀ {gs out : List Gate}, findPartner p gs = some out → Equivalent n m (p :: gs) out := by
  intro gs
  induction gs with
  | nil => intro out h; simp [findPartner] at h
  | cons g gs ih =>
      intro out h
      simp only [findPartner] at h
      by_cases heq : gatesEqual p g = true
      · rw [if_pos heq] at h
        simp only [Option.some.injEq] at h
        subst h
        have hcancel : Equivalent n m [p, g] [] :=
          Equivalent.gatesEqual_cancel heq (Wf_of_gatesEqual heq hwf)
            (isSelfInverse_of_gatesEqual heq)
        have := Equivalent.append_right (n := n) (m := m) gs hcancel
        simpa using this
      · rw [if_neg heq] at h
        by_cases hc : pairCommutes p g = true
        · rw [if_pos hc] at h
          simp only [Option.map_eq_some_iff] at h
          obtain ⟨out', hfind, rfl⟩ := h
          have hswap : Equivalent n m (p :: g :: gs) (g :: p :: gs) := by
            have := Equivalent.append_right (n := n) (m := m) gs
              (Equivalent.pairCommutes_swap (n := n) (m := m) hp hc)
            simpa using this
          refine Equivalent.trans hswap ?_
          have := Equivalent.append_left (n := n) (m := m) [g] (ih hfind)
          simpa using this
        · rw [if_neg hc] at h; simp at h

/-- One sweep-3 pass preserves semantics. -/
theorem cancelCommutingStep_correct {n m : Nat} : ∀ {gs out : List Gate},
    (∀ g ∈ gs, g.Wf) → cancelCommutingStep gs = some out → Equivalent n m out gs := by
  intro gs
  induction gs with
  | nil => intro out _ h; simp [cancelCommutingStep] at h
  | cons g gs ih =>
      intro out hwf h
      have hwf' : ∀ g' ∈ gs, g'.Wf := fun g' hg' => hwf g' (by simp [hg'])
      simp only [cancelCommutingStep] at h
      by_cases hpair : isPair g = true
      · rw [if_pos hpair] at h
        rcases hfind : findPartner g gs with _ | out'
        · rw [hfind] at h
          dsimp only at h
          simp only [Option.map_eq_some_iff] at h
          obtain ⟨out'', hstep, rfl⟩ := h
          simpa using Equivalent.append_left (n := n) (m := m) [g] (ih hwf' hstep)
        · rw [hfind] at h
          dsimp only at h
          simp only [Option.some.injEq] at h
          subst h
          exact (findPartner_correct hpair (hwf g (by simp)) hfind).symm
      · rw [if_neg hpair] at h
        simp only [Option.map_eq_some_iff] at h
        obtain ⟨out'', hstep, rfl⟩ := h
        simpa using Equivalent.append_left (n := n) (m := m) [g] (ih hwf' hstep)

/-- The gates of a sweep-3 output all come from the input. -/
theorem findPartner_mem {p : Gate} : ∀ {gs out : List Gate}, findPartner p gs = some out →
    ∀ g ∈ out, g ∈ gs := by
  intro gs
  induction gs with
  | nil => intro out h; simp [findPartner] at h
  | cons g gs ih =>
      intro out h x hx
      simp only [findPartner] at h
      by_cases heq : gatesEqual p g = true
      · rw [if_pos heq] at h
        simp only [Option.some.injEq] at h
        subst h
        exact List.mem_cons_of_mem _ hx
      · rw [if_neg heq] at h
        by_cases hc : pairCommutes p g = true
        · rw [if_pos hc] at h
          simp only [Option.map_eq_some_iff] at h
          obtain ⟨out', hfind, rfl⟩ := h
          rcases List.mem_cons.mp hx with rfl | hx
          · simp
          · exact List.mem_cons_of_mem _ (ih hfind x hx)
        · rw [if_neg hc] at h; simp at h

theorem cancelCommutingStep_mem : ∀ {gs out : List Gate}, cancelCommutingStep gs = some out →
    ∀ g ∈ out, g ∈ gs := by
  intro gs
  induction gs with
  | nil => intro out h; simp [cancelCommutingStep] at h
  | cons g gs ih =>
      intro out h x hx
      simp only [cancelCommutingStep] at h
      by_cases hpair : isPair g = true
      · rw [if_pos hpair] at h
        rcases hfind : findPartner g gs with _ | out'
        · rw [hfind] at h
          dsimp only at h
          simp only [Option.map_eq_some_iff] at h
          obtain ⟨out'', hstep, rfl⟩ := h
          rcases List.mem_cons.mp hx with rfl | hx
          · simp
          · exact List.mem_cons_of_mem _ (ih hstep x hx)
        · rw [hfind] at h
          dsimp only at h
          simp only [Option.some.injEq] at h
          subst h
          exact List.mem_cons_of_mem _ (findPartner_mem hfind x hx)
      · rw [if_neg hpair] at h
        simp only [Option.map_eq_some_iff] at h
        obtain ⟨out'', hstep, rfl⟩ := h
        rcases List.mem_cons.mp hx with rfl | hx
        · simp
        · exact List.mem_cons_of_mem _ (ih hstep x hx)

theorem cancelCommutingFuel_correct {n m : Nat} (fuel : Nat) (gs : List Gate)
    (hwf : ∀ g ∈ gs, g.Wf) : Equivalent n m (cancelCommutingFuel fuel gs) gs := by
  induction fuel generalizing gs with
  | zero => exact Equivalent.refl _ _ _
  | succ fuel ih =>
      rw [cancelCommutingFuel]
      rcases hstep : cancelCommutingStep gs with _ | gs'
      · exact Equivalent.refl _ _ _
      · exact Equivalent.trans
          (ih gs' fun g hg => hwf g (cancelCommutingStep_mem hstep g hg))
          (cancelCommutingStep_correct hwf hstep)

/-- **Sweep 3 is semantics preserving.** -/
theorem cancelCommutingPairs_correct {n m : Nat} (gs : List Gate) (hwf : ∀ g ∈ gs, g.Wf) :
    Equivalent n m (cancelCommutingPairs gs) gs :=
  cancelCommutingFuel_correct _ gs hwf

/-! ## Well-formedness is preserved

Sweeps 1 and 3 only delete gates; sweep 2 also *introduces* gates, but only single-wire
ones (`z`, `x`, `s`, `sdg`, `h`), for which `Gate.Wf` is vacuous. -/

theorem Wf_of_single {g : Gate} (h : g.qubitsOf.length ≤ 1) : g.Wf := by
  cases g <;> simp_all [Gate.qubitsOf, Gate.Wf]

theorem scanH_mem {q : Qubit} : ∀ {gs : List Gate} {r : HScan}, scanH q gs = some r →
    (∀ g ∈ r.before, g ∈ gs) ∧ (∀ g ∈ r.after, g ∈ gs) ∧ (∀ g ∈ r.rest, g ∈ gs) := by
  intro gs
  induction gs with
  | nil => intro r h; simp [scanH] at h
  | cons g gs ih =>
      intro r h
      simp only [scanH] at h
      by_cases hs : g.support q = true
      · rw [if_pos hs] at h
        rcases hd : diagonalK g q with _ | dk
        · rw [hd] at h
          by_cases hh : isH q g = true
          · rw [if_pos hh] at h
            simp only [Option.some.injEq] at h
            subst h
            exact ⟨by simp, by simp, fun x hx => List.mem_cons_of_mem _ hx⟩
          · rw [if_neg hh] at h; simp at h
        · rcases dk with _ | kg
          · rw [hd] at h; simp at h
          · rw [hd] at h
            simp only [Option.map_eq_some_iff] at h
            obtain ⟨r', hscan, rfl⟩ := h
            obtain ⟨hb, ha, hr⟩ := ih hscan
            refine ⟨by simp, ?_, fun x hx => List.mem_cons_of_mem _ (hr x hx)⟩
            intro x hx
            rcases List.mem_append.mp hx with hx | hx
            · exact List.mem_cons_of_mem _ (hb x hx)
            · exact List.mem_cons_of_mem _ (ha x hx)
      · rw [if_neg hs] at h
        simp only [Option.map_eq_some_iff] at h
        obtain ⟨r', hscan, rfl⟩ := h
        obtain ⟨hb, ha, hr⟩ := ih hscan
        by_cases hrun : r'.hasRun = true
        · rw [HScan.push_of_hasRun hrun]
          refine ⟨?_, fun x hx => List.mem_cons_of_mem _ (ha x hx),
            fun x hx => List.mem_cons_of_mem _ (hr x hx)⟩
          intro x hx
          rcases List.mem_cons.mp hx with rfl | hx
          · simp
          · exact List.mem_cons_of_mem _ (hb x hx)
        · simp only [Bool.not_eq_true] at hrun
          rw [HScan.push_of_not_hasRun hrun]
          refine ⟨fun x hx => List.mem_cons_of_mem _ (hb x hx), ?_,
            fun x hx => List.mem_cons_of_mem _ (hr x hx)⟩
          intro x hx
          rcases List.mem_cons.mp hx with rfl | hx
          · simp
          · exact List.mem_cons_of_mem _ (ha x hx)

theorem reduceAtH_wf {q : Qubit} {gs out : List Gate} (hwf : ∀ g ∈ gs, g.Wf)
    (h : reduceAtH q gs = some out) : ∀ g ∈ out, g.Wf := by
  have hsingle : ∀ g : Gate, g.qubitsOf.length ≤ 1 → g.Wf := fun g hg => Wf_of_single hg
  have hxw : (Gate.x q).Wf := hsingle _ (by simp [Gate.qubitsOf])
  have hzw : (Gate.z q).Wf := hsingle _ (by simp [Gate.qubitsOf])
  have hhw : (Gate.h q).Wf := hsingle _ (by simp [Gate.qubitsOf])
  have hsw : (Gate.s q).Wf := hsingle _ (by simp [Gate.qubitsOf])
  have hsdw : (Gate.sdg q).Wf := hsingle _ (by simp [Gate.qubitsOf])
  unfold reduceAtH at h
  rcases hx : scanXH q gs with _ | ⟨b₁, b₂, rest⟩
  · rw [hx] at h
    dsimp only at h
    rcases hscan : scanH q gs with _ | r
    · rw [hscan] at h; simp at h
    · rw [hscan] at h
      dsimp only at h
      obtain ⟨hb, ha, hr⟩ := scanH_mem hscan
      have hbw : ∀ g ∈ r.before, g.Wf := fun g hg => hwf g (hb g hg)
      have haw : ∀ g ∈ r.after, g.Wf := fun g hg => hwf g (ha g hg)
      have hrw : ∀ g ∈ r.rest, g.Wf := fun g hg => hwf g (hr g hg)
      by_cases hodd : r.k % 2 = 1
      · rw [if_pos hodd] at h; simp at h
      · rw [if_neg hodd] at h
        split at h
        · simp only [Option.some.injEq] at h
          subst h
          simp only [List.forall_mem_append]
          and_intros <;> assumption
        · split at h
          · simp only [Option.some.injEq] at h
            subst h
            simp only [List.forall_mem_append, List.forall_mem_cons]
            and_intros <;> assumption
          · split at h <;>
            · simp only [Option.some.injEq] at h
              subst h
              simp only [List.forall_mem_append, List.forall_mem_cons]
              and_intros <;> assumption
  · rw [hx] at h
    dsimp only at h
    simp only [Option.some.injEq] at h
    subst h
    obtain ⟨hgs, -, -⟩ := scanXH_spec hx
    have hmem : ∀ x ∈ b₁, x ∈ gs := by
      intro x hx'; rw [hgs]; exact List.mem_append_left _ hx'
    have hmem₂ : ∀ x ∈ b₂, x ∈ gs := by
      intro x hx'; rw [hgs]
      exact List.mem_append_right _ (List.mem_cons_of_mem _ (List.mem_append_left _ hx'))
    have hmem₃ : ∀ x ∈ rest, x ∈ gs := by
      intro x hx'; rw [hgs]
      exact List.mem_append_right _ (List.mem_cons_of_mem _
        (List.mem_append_right _ (List.mem_cons_of_mem _ hx')))
    have hb₁ : ∀ g ∈ b₁, g.Wf := fun g hg => hwf g (hmem g hg)
    have hb₂ : ∀ g ∈ b₂, g.Wf := fun g hg => hwf g (hmem₂ g hg)
    have hrest : ∀ g ∈ rest, g.Wf := fun g hg => hwf g (hmem₃ g hg)
    simp only [List.forall_mem_append, List.forall_mem_cons]
    and_intros <;> assumption

theorem reduceStep_wf : ∀ {gs out : List Gate}, (∀ g ∈ gs, g.Wf) → reduceStep gs = some out →
    ∀ g ∈ out, g.Wf := by
  intro gs
  induction gs with
  | nil => intro out _ h; simp [reduceStep] at h
  | cons g gs ih =>
      intro out hwf h
      have hwf' : ∀ g' ∈ gs, g'.Wf := fun g' hg' => hwf g' (by simp [hg'])
      simp only [reduceStep] at h
      cases hg : g with
      | h q =>
          subst hg
          dsimp only at h
          rcases hred : reduceAtH q gs with _ | out'
          · rw [hred] at h
            dsimp only at h
            simp only [Option.map_eq_some_iff] at h
            obtain ⟨out'', hstep, rfl⟩ := h
            intro x hx
            rcases List.mem_cons.mp hx with rfl | hx
            · exact hwf _ (by simp)
            · exact ih hwf' hstep x hx
          · rw [hred] at h
            dsimp only at h
            simp only [Option.some.injEq] at h
            subst h
            exact reduceAtH_wf hwf' hred
      | _ =>
          subst hg
          dsimp only at h
          simp only [Option.map_eq_some_iff] at h
          obtain ⟨out'', hstep, rfl⟩ := h
          intro x hx
          rcases List.mem_cons.mp hx with rfl | hx
          · exact hwf _ (by simp)
          · exact ih hwf' hstep x hx

theorem reduceHadamardsFuel_wf (fuel : Nat) : ∀ {gs : List Gate}, (∀ g ∈ gs, g.Wf) →
    ∀ g ∈ reduceHadamardsFuel fuel gs, g.Wf := by
  induction fuel with
  | zero => intro gs hwf; exact hwf
  | succ fuel ih =>
      intro gs hwf
      rw [reduceHadamardsFuel]
      rcases hstep : reduceStep gs with _ | gs'
      · exact hwf
      · exact ih (reduceStep_wf hwf hstep)

theorem reduceHadamards_wf {gs : List Gate} (hwf : ∀ g ∈ gs, g.Wf) :
    ∀ g ∈ reduceHadamards gs, g.Wf := reduceHadamardsFuel_wf _ hwf

/-! ## Operand ranges

The same three sweeps, against the other half of `RawCircuit`'s structural invariant. The
argument is shorter than the `Wf` one only because the gates the Hadamard rule invents —
`x`, `z`, `h`, `s`, `sdg` — all sit on the wire of the `h` that opened the run, so their
range is the range of a gate the sweep was already given. -/

theorem reduceAtH_inRange {n m : Nat} {q : Qubit} {gs out : List Gate} (hq : q < n)
    (hwf : ∀ g ∈ gs, g.InRange n m) (h : reduceAtH q gs = some out) :
    ∀ g ∈ out, g.InRange n m := by
  have hxw : (Gate.x q).InRange n m := Gate.inRange_of_qubitsOf_eq hq rfl rfl
  have hzw : (Gate.z q).InRange n m := Gate.inRange_of_qubitsOf_eq hq rfl rfl
  have hhw : (Gate.h q).InRange n m := Gate.inRange_of_qubitsOf_eq hq rfl rfl
  have hsw : (Gate.s q).InRange n m := Gate.inRange_of_qubitsOf_eq hq rfl rfl
  have hsdw : (Gate.sdg q).InRange n m := Gate.inRange_of_qubitsOf_eq hq rfl rfl
  unfold reduceAtH at h
  rcases hx : scanXH q gs with _ | ⟨b₁, b₂, rest⟩
  · rw [hx] at h
    dsimp only at h
    rcases hscan : scanH q gs with _ | r
    · rw [hscan] at h; simp at h
    · rw [hscan] at h
      dsimp only at h
      obtain ⟨hb, ha, hr⟩ := scanH_mem hscan
      have hbw : ∀ g ∈ r.before, g.InRange n m := fun g hg => hwf g (hb g hg)
      have haw : ∀ g ∈ r.after, g.InRange n m := fun g hg => hwf g (ha g hg)
      have hrw : ∀ g ∈ r.rest, g.InRange n m := fun g hg => hwf g (hr g hg)
      by_cases hodd : r.k % 2 = 1
      · rw [if_pos hodd] at h; simp at h
      · rw [if_neg hodd] at h
        split at h
        · simp only [Option.some.injEq] at h
          subst h
          simp only [List.forall_mem_append]
          and_intros <;> assumption
        · split at h
          · simp only [Option.some.injEq] at h
            subst h
            simp only [List.forall_mem_append, List.forall_mem_cons]
            and_intros <;> assumption
          · split at h <;>
            · simp only [Option.some.injEq] at h
              subst h
              simp only [List.forall_mem_append, List.forall_mem_cons]
              and_intros <;> assumption
  · rw [hx] at h
    dsimp only at h
    simp only [Option.some.injEq] at h
    subst h
    obtain ⟨hgs, -, -⟩ := scanXH_spec hx
    have hmem : ∀ x ∈ b₁, x ∈ gs := by
      intro x hx'; rw [hgs]; exact List.mem_append_left _ hx'
    have hmem₂ : ∀ x ∈ b₂, x ∈ gs := by
      intro x hx'; rw [hgs]
      exact List.mem_append_right _ (List.mem_cons_of_mem _ (List.mem_append_left _ hx'))
    have hmem₃ : ∀ x ∈ rest, x ∈ gs := by
      intro x hx'; rw [hgs]
      exact List.mem_append_right _ (List.mem_cons_of_mem _
        (List.mem_append_right _ (List.mem_cons_of_mem _ hx')))
    have hb₁ : ∀ g ∈ b₁, g.InRange n m := fun g hg => hwf g (hmem g hg)
    have hb₂ : ∀ g ∈ b₂, g.InRange n m := fun g hg => hwf g (hmem₂ g hg)
    have hrest : ∀ g ∈ rest, g.InRange n m := fun g hg => hwf g (hmem₃ g hg)
    simp only [List.forall_mem_append, List.forall_mem_cons]
    and_intros <;> assumption

theorem reduceStep_inRange {n m : Nat} : ∀ {gs out : List Gate},
    (∀ g ∈ gs, g.InRange n m) → reduceStep gs = some out → ∀ g ∈ out, g.InRange n m := by
  intro gs
  induction gs with
  | nil => intro out _ h; simp [reduceStep] at h
  | cons g gs ih =>
      intro out hwf h
      have hwf' : ∀ g' ∈ gs, g'.InRange n m := fun g' hg' => hwf g' (by simp [hg'])
      simp only [reduceStep] at h
      cases hg : g with
      | h q =>
          subst hg
          dsimp only at h
          rcases hred : reduceAtH q gs with _ | out'
          · rw [hred] at h
            dsimp only at h
            simp only [Option.map_eq_some_iff] at h
            obtain ⟨out'', hstep, rfl⟩ := h
            intro x hx
            rcases List.mem_cons.mp hx with rfl | hx
            · exact hwf _ (by simp)
            · exact ih hwf' hstep x hx
          · rw [hred] at h
            dsimp only at h
            simp only [Option.some.injEq] at h
            subst h
            exact reduceAtH_inRange ((hwf (Gate.h q) (by simp)).qubits q (by simp [Gate.qubitsOf]))
              hwf' hred
      | _ =>
          subst hg
          dsimp only at h
          simp only [Option.map_eq_some_iff] at h
          obtain ⟨out'', hstep, rfl⟩ := h
          intro x hx
          rcases List.mem_cons.mp hx with rfl | hx
          · exact hwf _ (by simp)
          · exact ih hwf' hstep x hx

theorem reduceHadamardsFuel_inRange {n m : Nat} (fuel : Nat) : ∀ {gs : List Gate},
    (∀ g ∈ gs, g.InRange n m) → ∀ g ∈ reduceHadamardsFuel fuel gs, g.InRange n m := by
  induction fuel with
  | zero => intro gs hwf; exact hwf
  | succ fuel ih =>
      intro gs hwf
      rw [reduceHadamardsFuel]
      rcases hstep : reduceStep gs with _ | gs'
      · exact hwf
      · exact ih (reduceStep_inRange hwf hstep)

theorem reduceHadamards_inRange {n m : Nat} {gs : List Gate} (hwf : ∀ g ∈ gs, g.InRange n m) :
    ∀ g ∈ reduceHadamards gs, g.InRange n m := reduceHadamardsFuel_inRange _ hwf

theorem cancelCommutingFuel_wf (fuel : Nat) : ∀ {gs : List Gate}, (∀ g ∈ gs, g.Wf) →
    ∀ g ∈ cancelCommutingFuel fuel gs, g.Wf := by
  induction fuel with
  | zero => intro gs hwf; exact hwf
  | succ fuel ih =>
      intro gs hwf
      rw [cancelCommutingFuel]
      rcases hstep : cancelCommutingStep gs with _ | gs'
      · exact hwf
      · exact ih fun g hg => hwf g (cancelCommutingStep_mem hstep g hg)

theorem cancelCommutingPairs_wf {gs : List Gate} (hwf : ∀ g ∈ gs, g.Wf) :
    ∀ g ∈ cancelCommutingPairs gs, g.Wf := cancelCommutingFuel_wf _ hwf

theorem cancelPairs_wf {gs : List Gate} (hwf : ∀ g ∈ gs, g.Wf) :
    ∀ g ∈ cancelPairs gs, g.Wf := fun g hg => hwf g (cancelPairs_mem gs g hg)

/-! ## The pass

`CancelGates::run` alternates the three sweeps to a combined fixpoint: dropping gates
between two `H`s or two `CNOT`s exposes new reducible runs, and a rewrite that emits an `X`
or `Z` exposes a new cancellable pair. The Rust loop stops when no sweep reports a change;
here the same test is "the round changed nothing", and the round count is bounded by fuel —
each productive round removes a gate or a Hadamard.
-/

/-- One round of all three sweeps, iterated to a fixpoint. -/
def cancelGatesLoop : Nat → List Gate → List Gate
  | 0, gs => gs
  | fuel + 1, gs =>
      let next := cancelPairs (cancelCommutingPairs (reduceHadamards gs))
      if next = gs then gs else cancelGatesLoop fuel next

/-- The gate-level `CancelGates` transformation. -/
def cancelGates (gs : List Gate) : List Gate :=
  cancelGatesLoop (2 * gs.length + 1) (cancelPairs gs)

theorem cancelGatesLoop_wf : ∀ (fuel : Nat) {gs : List Gate}, (∀ g ∈ gs, g.Wf) →
    ∀ g ∈ cancelGatesLoop fuel gs, g.Wf := by
  intro fuel
  induction fuel with
  | zero => intro gs hwf; exact hwf
  | succ fuel ih =>
      intro gs hwf
      rw [cancelGatesLoop]
      split
      · exact hwf
      · exact ih (cancelPairs_wf (cancelCommutingPairs_wf (reduceHadamards_wf hwf)))

theorem cancelGatesLoop_correct {n m : Nat} : ∀ (fuel : Nat) {gs : List Gate},
    (∀ g ∈ gs, g.Wf) → Equivalent n m (cancelGatesLoop fuel gs) gs := by
  intro fuel
  induction fuel with
  | zero => intro gs _; exact Equivalent.refl _ _ _
  | succ fuel ih =>
      intro gs hwf
      rw [cancelGatesLoop]
      split
      · exact Equivalent.refl _ _ _
      · have hwf₁ := reduceHadamards_wf hwf
        have hwf₂ := cancelCommutingPairs_wf hwf₁
        refine Equivalent.trans (ih (cancelPairs_wf hwf₂)) ?_
        refine Equivalent.trans (cancelPairs_correct _ hwf₂) ?_
        exact Equivalent.trans (cancelCommutingPairs_correct _ hwf₁)
          (reduceHadamards_correct _)

theorem cancelGates_wf {gs : List Gate} (hwf : ∀ g ∈ gs, g.Wf) :
    ∀ g ∈ cancelGates gs, g.Wf :=
  cancelGatesLoop_wf _ (cancelPairs_wf hwf)

/-- The two cancelling sweeps only ever *delete*, so they preserve any gate property at
all — including both halves of the structural invariant. -/
theorem cancelCommutingFuel_pred {P : Gate → Prop} (fuel : Nat) : ∀ {gs : List Gate},
    (∀ g ∈ gs, P g) → ∀ g ∈ cancelCommutingFuel fuel gs, P g := by
  induction fuel with
  | zero => intro gs h; exact h
  | succ fuel ih =>
      intro gs h
      rw [cancelCommutingFuel]
      rcases hstep : cancelCommutingStep gs with _ | gs'
      · exact h
      · exact ih fun g hg => h g (cancelCommutingStep_mem hstep g hg)

theorem cancelCommutingPairs_pred {P : Gate → Prop} {gs : List Gate} (h : ∀ g ∈ gs, P g) :
    ∀ g ∈ cancelCommutingPairs gs, P g := cancelCommutingFuel_pred _ h

theorem cancelPairs_pred {P : Gate → Prop} {gs : List Gate} (h : ∀ g ∈ gs, P g) :
    ∀ g ∈ cancelPairs gs, P g := fun g hg => h g (cancelPairs_mem gs g hg)

theorem cancelGatesLoop_inRange {n m : Nat} : ∀ (fuel : Nat) {gs : List Gate},
    (∀ g ∈ gs, g.InRange n m) → ∀ g ∈ cancelGatesLoop fuel gs, g.InRange n m := by
  intro fuel
  induction fuel with
  | zero => intro gs h; exact h
  | succ fuel ih =>
      intro gs h
      rw [cancelGatesLoop]
      split
      · exact h
      · exact ih (cancelPairs_pred (cancelCommutingPairs_pred (reduceHadamards_inRange h)))

/-- **`CancelGates` keeps every operand in range.** -/
theorem cancelGates_inRange {n m : Nat} {gs : List Gate} (h : ∀ g ∈ gs, g.InRange n m) :
    ∀ g ∈ cancelGates gs, g.InRange n m :=
  cancelGatesLoop_inRange _ (cancelPairs_pred h)

/-- **`CancelGates` preserves semantics.** -/
theorem cancelGates_correct {n m : Nat} (gs : List Gate) (hwf : ∀ g ∈ gs, g.Wf) :
    Equivalent n m (cancelGates gs) gs :=
  Equivalent.trans (cancelGatesLoop_correct _ (cancelPairs_wf hwf))
    (cancelPairs_correct _ hwf)

/-- Run gate cancellation on a raw circuit. -/
def cancelGatesCircuit (c : RawCircuit) : RawCircuit := c.withGates (cancelGates c.gates)

/-- **The `CancelGates` pass**, with its correctness proof as a field. -/
def CancelGates : Pass where
  name := "Gate cancellation"
  run := fun c => ⟨cancelGatesCircuit c.raw, c.numQubits_eq, c.numCbits_eq,
    cancelGates_wf c.wf⟩
  correct c := cancelGates_correct c.raw.gates c.wf

end
end TzapLean
